defmodule QuickBEAM.BeamDisasm do
  @moduledoc """
  Disassembled BEAM module generated by the `:beam` backend.

  Returned by `QuickBEAM.disasm/2` and `QuickBEAM.disasm/3` when the
  runtime is in `:beam` mode.
  """

  defstruct [
    :module,
    :js_name,
    :entry,
    error: nil,
    exports: [],
    attributes: [],
    compile_info: [],
    code: [],
    children: []
  ]

  @type beam_function :: {:function, atom(), non_neg_integer(), non_neg_integer(), [tuple()]}

  @type t :: %__MODULE__{
          module: module() | nil,
          js_name: String.t() | nil,
          entry: atom() | nil,
          error: term() | nil,
          exports: [tuple()],
          attributes: keyword(),
          compile_info: keyword(),
          code: [beam_function()],
          children: [t()]
        }

  @doc false
  def from_beam_file({:beam_file, module, exports, attributes, compile_info, code}, opts \\ []) do
    %__MODULE__{
      module: module,
      js_name: Keyword.get(opts, :js_name),
      entry: Keyword.get(opts, :entry, :run),
      error: Keyword.get(opts, :error),
      exports: exports,
      attributes: attributes,
      compile_info: compile_info,
      code: code,
      children: Keyword.get(opts, :children, [])
    }
  end
end
