pub const wamr = @cImport({
    @cDefine("WASM_ENABLE_INTERP", "1");
    @cDefine("WASM_ENABLE_AOT", "0");
    @cDefine("WASM_ENABLE_FAST_INTERP", "0");
    @cDefine("WASM_ENABLE_LIBC_BUILTIN", "0");
    @cDefine("WASM_ENABLE_LIBC_WASI", "0");
    @cDefine("WASM_ENABLE_MULTI_MODULE", "0");
    @cDefine("WASM_ENABLE_BULK_MEMORY", "1");
    @cDefine("WASM_ENABLE_REF_TYPES", "1");
    @cDefine("WASM_ENABLE_SIMD", "0");
    @cDefine("WASM_ENABLE_TAIL_CALL", "1");
    @cDefine("WASM_ENABLE_MEMORY64", "0");
    @cDefine("WASM_ENABLE_GC", "0");
    @cDefine("WASM_ENABLE_THREAD_MGR", "0");
    @cDefine("WASM_ENABLE_SHARED_MEMORY", "0");
    @cDefine("WASM_ENABLE_EXCE_HANDLING", "0");
    @cDefine("WASM_ENABLE_MINI_LOADER", "0");
    @cDefine("WASM_ENABLE_WAMR_COMPILER", "0");
    @cDefine("WASM_ENABLE_JIT", "0");
    @cDefine("WASM_ENABLE_FAST_JIT", "0");
    @cDefine("WASM_ENABLE_DEBUG_INTERP", "0");
    @cDefine("WASM_ENABLE_INSTRUCTION_METERING", "1");
    @cDefine("WASM_ENABLE_DUMP_CALL_STACK", "0");
    @cDefine("WASM_ENABLE_PERF_PROFILING", "0");
    @cDefine("WASM_ENABLE_LOAD_CUSTOM_SECTION", "0");
    @cDefine("WASM_ENABLE_CUSTOM_NAME_SECTION", "1");
    @cDefine("WASM_ENABLE_GLOBAL_HEAP_POOL", "0");
    @cDefine("WASM_ENABLE_SPEC_TEST", "0");
    @cDefine("WASM_ENABLE_LABELS_AS_VALUES", "1");
    @cDefine("WASM_ENABLE_WASM_CACHE", "0");
    @cDefine("WASM_ENABLE_STRINGREF", "0");
    @cDefine("WASM_MEM_ALLOC_WITH_SYSTEM_ALLOCATOR", "1");
    @cDefine("WASM_RUNTIME_API_EXTERN", "");
    @cDefine("BH_MALLOC", "malloc");
    @cDefine("BH_FREE", "free");
    @cInclude("wamr_bridge.h");
});
