Mix.Task.run("app.start")

Code.require_file("../test/support/vm_compiler_audit.ex", __DIR__)

cases = [
  {"derived constructor primitive return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return 1 } } new B()"},
  {"with property assignment", "let o={x:1}; with(o){ x=2; } o.x"},
  {"with missing global assignment", "var x=1; let o={}; with(o){ x=2; } x"},
  {"with property update", "let o={x:1}; with(o){ x++; } o.x"},
  {"with unscopables fallback",
   "var x=1; let o={x:2, [Symbol.unscopables]: {x:true}}; with(o){ x=3; } [x,o.x]"},
  {"async function invocation", "async function f(){ return 1 } f()"},
  {"generator next value", "function* g(){ yield 1; return 2 } let it=g(); it.next().value"},
  {"dynamic import rejection", "import('x')"},
  {"derived constructor undefined return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return undefined } } new B().a"},
  {"derived constructor object return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return {b:2} } } new B().b"},
  {"with captured assignment",
   "var out; function f(){ let x=1; function g(){ let o={}; with(o){ x=2 } return x } return g() } f()"},
  {"with local fallback read", "let o={}; let x=1; with(o){ x }"},
  {"with delete property", "let o={x:1}; with(o){ delete x; } 'x' in o"},
  {"async await value", "async function f(){ return await 2 } f()"},
  {"async await resolved promise", "async function f(){ return await Promise.resolve(3) } f()"},
  {"generator two next values",
   "function* g(){ yield 1; yield 2; return 3 } let it=g(); it.next().value + it.next().value"},
  {"generator return value",
   "function* g(){ yield 1; return 3 } let it=g(); it.next(); it.next().value"},
  {"async caught throw", "async function f(){ try { throw 4 } catch(e) { return e } } f()"},
  {"with fallback method call", "function m(){return 3}; let o={}; with(o){ m() }"},
  {"with property method call", "let o={x:2, m(){return this.x}}; with(o){ m() }"},
  {"with property function this", "let o={x:3, m:function(){return this.x}}; with(o){ m() }"},
  {"with property arrow call", "let o={x:4, m:()=>5}; with(o){ m() }"},
  {"with method arguments", "let o={m(a,b){return a+b}}; with(o){ m(2,3) }"},
  {"with method update", "let o={x:1, inc(){this.x++; return this.x}}; with(o){ inc() }"},
  {"with missing property delete", "let o={}; with(o){ delete x }"},
  {"with captured update",
   "function f(){ let x=1; function g(){ let o={}; with(o){ x++ } return x } return g() } f()"},
  {"with captured unscopables fallback",
   "function f(){ let x=1; function g(){ let o={x:2,[Symbol.unscopables]:{x:true}}; with(o){ x=3 } return [x,o.x] } return g() } f()"},
  {"async await chained promise",
   "async function f(){ return await Promise.resolve(1).then(function(v){ return v+1 }) } f()"},
  {"async nested await",
   "async function f(){ return await Promise.resolve(await Promise.resolve(4)) } f()"},
  {"async rejection catch",
   "async function f(){ return await Promise.reject('err').catch(function(e){ return e + '!' }) } f()"},
  {"generator third next value",
   "function* g(){ yield 1; yield 2; return 3 } let it=g(); it.next(); it.next(); it.next().value"},
  {"generator return method", "function* g(){ yield 1; yield 2 } let it=g(); it.return(9).value"},
  {"derived constructor new target",
   "class A { constructor(){ this.v = new.target.name } } class B extends A { constructor(){ super() } } new B().v"},
  {"computed class value invoked", "let o={ [class C{}]: 1 }; 1"},
  {"custom iterator loop value",
   "let it={ [Symbol.iterator](){ return { i:0, next(){ return this.i++ < 1 ? {value:7, done:false} : {done:true}; } } } }; let s=0; for (let x of it) s+=x; s"},
  {"with fallback delete global", "var x=1; let o={}; with(o){ delete x } x"},
  {"with unscopables read fallback",
   "var x=1; let o={x:2,[Symbol.unscopables]:{x:true}}; with(o){ x }"},
  {"async multiple awaits sum",
   "async function f(){ let a=await 1; let b=await 2; return a+b } f()"},
  {"async promise all length",
   "async function f(){ let r = await Promise.all([Promise.resolve(1), Promise.resolve(2)]); return r.length } f()"},
  {"generator next done flag", "function* g(){ yield 1 } let it=g(); it.next(); it.next().done"},
  {"generator send ignored first",
   "function* g(){ let x = yield 1; return x } let it=g(); it.next(5).value"},
  {"generator send second",
   "function* g(){ let x = yield 1; return x } let it=g(); it.next(); it.next(7).value"},
  {"derived super argument",
   "class A { constructor(x){ this.x=x } } class B extends A { constructor(){ super(5) } } new B().x"},
  {"super method call",
   "class A { m(){ return 1 } } class B extends A { m(){ return super.m()+1 } } new B().m()"},
  {"private field method", "class A { #x=1; m(){ return this.#x } } new A().m()"},
  {"array destructuring default", "let [a=3] = []; a"},
  {"object spread override", "let o={...{x:1}, x:2}; o.x"},
  {"optional chain method", "let o={x:1,m(){return this.x}}; o?.m()"},
  {"nullish assignment", "let x=null; x ??= 3; x"},
  {"logical assignment", "let x=0; x ||= 4; x"},
  {"regexp exec group", "/(a+)/.exec('aa')[1]"},
  {"typed array value", "let a=new Uint8Array(2); a[0]=255; a[0]"},
  {"map set get", "let m=new Map(); m.set('x', 2); m.get('x')"},
  {"set has", "let s=new Set(); s.add(3); s.has(3)"},
  {"string includes", "'quickbeam'.includes('beam')"},
  {"array map length", "[1,2,3].map(function(x){return x+1}).length"},
  {"array reduce sum", "[1,2,3].reduce(function(a,b){return a+b},0)"},
  {"object keys length", "Object.keys({a:1,b:2}).length"},
  {"json stringify object", "JSON.stringify({a:1})"},
  {"date now type", "typeof Date.now()"},
  {"bigint addition", "1n + 2n"},
  {"bigint compare", "2n > 1n"},
  {"symbol property", "let s=Symbol('x'); let o={[s]:3}; o[s]"},
  {"class static field", "class A { static x=3; static m(){return this.x} } A.m()"},
  {"private method", "class A { #m(){return 4} m(){return this.#m()} } new A().m()"},
  {"static super method",
   "class A { static m(){return 1} } class B extends A { static m(){return super.m()+2} } B.m()"},
  {"try finally return override", "function f(){ try { return 1 } finally { return 2 } } f()"},
  {"catch binding", "try { throw 5 } catch(e) { e+1 }"},
  {"for in keys", "let s=''; for (let k in {a:1,b:2}) s+=k; s.length"},
  {"for of destructuring", "let s=0; for (let [x] of [[1],[2]]) s+=x; s"},
  {"spread constructor", "function A(a,b){this.v=a+b}; new A(...[1,2]).v"},
  {"rest parameter", "function f(...xs){ return xs.length + xs[0] } f(3,4)"},
  {"array filter join", "[1,2,3,4].filter(function(x){return x%2===0}).join(',')"},
  {"array find", "[1,2,3].find(function(x){return x>1})"},
  {"array includes", "[1,2,3].includes(2)"},
  {"string replace", "'a-b'.replace('-', '+')"},
  {"string split length", "'a,b,c'.split(',').length"},
  {"number to fixed", "(1.25).toFixed(1)"},
  {"math max", "Math.max(1,5,3)"},
  {"object assign", "let o=Object.assign({a:1},{b:2}); o.b"},
  {"object define property", "let o={}; Object.defineProperty(o,'x',{value:4}); o.x"},
  {"property descriptor", "let o={x:1}; Object.getOwnPropertyDescriptor(o,'x').value"},
  {"set size", "let s=new Set([1,2,2]); s.size"},
  {"map size", "let m=new Map([['a',1],['b',2]]); m.size"},
  {"weakmap basic", "let k={}; let m=new WeakMap(); m.set(k,3); m.get(k)"},
  {"uint16 overflow", "let a=new Uint16Array(1); a[0]=65537; a[0]"},
  {"text encoder length", "new TextEncoder().encode('abc').length"},
  {"url pathname", "new URL('https://x.test/a?b=1').pathname"},
  {"regexp replace capture", "'abc'.replace(/(b)/, '[$1]')"},
  {"class getter setter",
   "class A { set x(v){this.v=v} get x(){return this.v} } let a=new A(); a.x=5; a.x"},
  {"static block", "class A { static { this.x=6 } } A.x"},
  {"private static field", "class A { static #x=7; static m(){return this.#x} } A.m()"},
  {"optional call missing", "let f=null; f?.() === undefined"},
  {"optional chain element", "let o={a:[3]}; o?.a?.[0]"},
  {"nested destructuring", "let {a:{b}}={a:{b:8}}; b"},
  {"rest object", "let {a,...r}={a:1,b:2}; r.b"},
  {"spread array", "let a=[1,...[2,3]]; a.length"},
  {"default param closure", "function f(x=3){return function(){return x}} f()()"},
  {"arrow this lexical", "let o={x:4,m(){let f=()=>this.x; return f()}}; o.m()"},
  {"eval local", "function f(){ var x=1; eval('x=2'); return x } f()"},
  {"direct eval expr", "eval('1+2')"},
  {"function bind", "function f(a,b){return a+b}; f.bind(null,2)(3)"},
  {"call apply", "function f(a,b){return a+b}; f.apply(null,[2,4])"},
  {"proxy get", "let p=new Proxy({x:1},{get(t,k){return t[k]+1}}); p.x"},
  {"proxy set", "let o={}; let p=new Proxy(o,{set(t,k,v){t[k]=v+1; return true}}); p.x=2; o.x"},
  {"reflect get", "Reflect.get({x:2}, 'x')"},
  {"reflect set", "let o={}; Reflect.set(o,'x',3); o.x"},
  {"array from set", "Array.from(new Set([1,2])).length"},
  {"array flat", "[1,[2,[3]]].flat(2).length"},
  {"array flatmap", "[1,2].flatMap(function(x){return [x,x]}).length"},
  {"string match", "'abc'.match(/b/)[0]"},
  {"template tag", "function tag(s,v){return s[0]+v}; tag`x${3}`"},
  {"computed property assignment", "let k='x'; let o={}; o[k]=4; o.x"},
  {"super setter",
   "class A { set x(v){this.y=v} } class B extends A { m(){ super.x=5; return this.y } } new B().m()"},
  {"static super setter",
   "class A { static set x(v){this.y=v} } class B extends A { static m(){ super.x=6; return this.y } } B.m()"},
  {"private setter",
   "class A { #x=0; set x(v){this.#x=v} get x(){return this.#x} } let a=new A(); a.x=7; a.x"},
  {"class field arrow", "class A { x=1; m=()=>this.x } new A().m()"},
  {"static private method",
   "class A { static #m(){return 8} static m(){return this.#m()} } A.m()"},
  {"object entries", "Object.entries({a:1,b:2}).length"},
  {"object from entries", "Object.fromEntries([['x',1]]).x"},
  {"assign accessor", "let o={set x(v){this.y=v}}; Object.assign(o,{x:2}); o.y"},
  {"intl unavailable type", "typeof Intl"},
  {"parse int", "parseInt('10', 10)"},
  {"is finite", "Number.isFinite(3)"},
  {"nan compare", "Number.isNaN(NaN)"},
  {"error message", "try { throw new Error('boom') } catch(e) { e.message }"},
  {"finally mutation", "let x=1; try { x=2 } finally { x=3 } x"},
  {"switch fallthrough", "let x=0; switch(1){case 1:x++; case 2:x++;} x"},
  {"labeled break", "let x=0; outer: while(true){ x=1; break outer; x=2 } x"},
  {"do while", "let x=0; do { x++ } while(x<3); x"},
  {"uint8 clamped", "let a=new Uint8ClampedArray(1); a[0]=300; a[0]"},
  {"array buffer byte length", "new ArrayBuffer(8).byteLength"},
  {"typed array slice", "let a=new Uint8Array([1,2,3]); a.slice(1)[0]"},
  {"map iteration sum", "let m=new Map([[1,2],[3,4]]); let s=0; for (let [k,v] of m) s+=k+v; s"},
  {"set iteration sum", "let s=new Set([1,2]); let n=0; for (let x of s) n+=x; n"},
  {"string iterator", "let s=''; for (let c of 'ab') s+=c; s"},
  {"object values length", "Object.values({a:1,b:2}).length"},
  {"object hasown", "Object.hasOwn({x:1}, 'x')"},
  {"object create proto", "let p={x:1}; let o=Object.create(p); o.x"},
  {"property getter descriptor",
   "let o={get x(){return 2}}; Object.getOwnPropertyDescriptor(o,'x').get.call(o)"},
  {"define getter", "let o={}; Object.defineProperty(o,'x',{get(){return 4}}); o.x"},
  {"delete property result", "let o={x:1}; delete o.x"},
  {"in prototype", "let p={x:1}; let o=Object.create(p); 'x' in o"},
  {"instanceof class", "class A{}; new A() instanceof A"},
  {"new bound function", "function A(x){this.x=x}; let B=A.bind(null,5); new B().x"},
  {"symbol for key", "Symbol.keyFor(Symbol.for('x'))"},
  {"global this math", "globalThis.Math === Math"},
  {"json parse", "JSON.parse('{\"x\":2}').x"},
  {"json parse reviver", "JSON.parse('{\"x\":2}', function(k,v){return k==='x'?v+1:v}).x"},
  {"regexp test global", "let r=/a/g; r.test('a') && r.lastIndex"},
  {"regexp flags", "/a/gi.flags"},
  {"string pad", "'x'.padStart(3,'0')"},
  {"string trim", "' x '.trim()"},
  {"number parse float", "Number.parseFloat('1.5')"},
  {"math trunc", "Math.trunc(1.9)"},
  {"array sort", "[3,1,2].sort()[0]"},
  {"array every", "[1,2,3].every(x=>x>0)"},
  {"array some", "[1,2,3].some(x=>x>2)"},
  {"array fill", "let a=[0,0,0]; a.fill(5,1); a[1]"},
  {"array copyWithin", "let a=[1,2,3]; a.copyWithin(1,0,1); a[1]"},
  {"array at", "[1,2,3].at(-1)"},
  {"string startswith", "'quickbeam'.startsWith('quick')"},
  {"string endswith", "'quickbeam'.endsWith('beam')"},
  {"string repeat", "'ab'.repeat(3)"},
  {"string code point", "'😀'.codePointAt(0)"},
  {"string from code point", "String.fromCodePoint(65)"},
  {"array reverse", "let a=[1,2,3]; a.reverse()[0]"},
  {"array shift", "let a=[1,2]; a.shift()+a.length"},
  {"array unshift", "let a=[2]; a.unshift(1); a[0]+a.length"},
  {"array push pop", "let a=[]; a.push(1,2); a.pop()+a.length"},
  {"array splice", "let a=[1,2,3]; a.splice(1,1,4); a[1]"},
  {"array concat", "[1].concat([2,3]).length"},
  {"array lastindexof", "[1,2,1].lastIndexOf(1)"},
  {"array join sparse", "[1,,3].join('-')"},
  {"math sign", "Math.sign(-3)"},
  {"math hypot", "Math.hypot(3,4)"},
  {"math clz32", "Math.clz32(1)"},
  {"number is integer", "Number.isInteger(3.0)"},
  {"number epsilon type", "typeof Number.EPSILON"},
  {"parse float global", "parseFloat('2.5x')"},
  {"weakset has", "let k={}; let s=new WeakSet(); s.add(k); s.has(k)"},
  {"map delete", "let m=new Map([[1,2]]); m.delete(1) && m.size"},
  {"set delete", "let s=new Set([1]); s.delete(1) && s.size"},
  {"map forEach", "let m=new Map([[1,2],[3,4]]); let s=0; m.forEach((v,k)=>s+=v+k); s"},
  {"object get prototype", "let p={}; let o=Object.create(p); Object.getPrototypeOf(o) === p"},
  {"object set prototype", "let p={x:1}; let o={}; Object.setPrototypeOf(o,p); o.x"},
  {"reflect has", "Reflect.has({x:1}, 'x')"},
  {"proxy has", "let p=new Proxy({}, {has(){return true}}); 'x' in p"},
  {"proxy ownkeys",
   "let p=new Proxy({}, {ownKeys(){return ['x']}, getOwnPropertyDescriptor(){return {configurable:true, enumerable:true}}}); Object.keys(p)[0]"},
  {"destructuring rest array", "let [a,...r]=[1,2,3]; r.length+a"},
  {"parameter destructuring", "function f({x}, [y]){return x+y}; f({x:1}, [2])"},
  {"computed object method", "let k='m'; let o={ [k](){return 6} }; o.m()"},
  {"async arrow", "let f=async x=>await x+1; f(2)"},
  {"class extends expression", "let B=class {m(){return 1}}; class A extends B {}; new A().m()"},
  {"static block private",
   "class A { static #x; static { this.#x=4 } static m(){return this.#x} } A.m()"},
  {"private in true", "class A { #x; has(o){return #x in o} } let a=new A(); a.has(a)"},
  {"private in false", "class A { #x; has(o){return #x in o} } new A().has({})"},
  {"try catch finally", "let x=0; try { throw 1 } catch(e){ x=e } finally { x+=2 } x"},
  {"nested switch", "let x=0; switch(2){case 1:x=1;break;case 2:switch(1){case 1:x=3}} x"},
  {"date full year", "new Date(0).getFullYear()"},
  {"date utc year", "new Date(Date.UTC(2020,0,1)).getUTCFullYear()"},
  {"date parse type", "typeof Date.parse('2020-01-01T00:00:00Z')"},
  {"date to json type", "typeof new Date(0).toJSON()"},
  {"promise all values",
   "async function f(){ let r=await Promise.all([1, Promise.resolve(2)]); return r[0]+r[1] } f()"},
  {"promise race value",
   "async function f(){ return await Promise.race([Promise.resolve(3)]) } f()"},
  {"promise all settled length",
   "async function f(){ let r=await Promise.allSettled([Promise.resolve(1)]); return r.length } f()"},
  {"async finally return", "async function f(){ try { return 1 } finally { } } f()"},
  {"async finally override", "async function f(){ try { return 1 } finally { return 2 } } f()"},
  {"async catch finally",
   "async function f(){ try { throw 1 } catch(e){ return e+1 } finally {} } f()"},
  {"generator finally return",
   "function* g(){ try { yield 1 } finally { return 4 } } let it=g(); it.next(); it.next().value"},
  {"generator yield in finally",
   "function* g(){ try { yield 1 } finally { yield 2 } } let it=g(); it.next(); it.next().value"},
  {"url search params get", "new URL('https://x.test/?a=1').searchParams.get('a')"},
  {"url href set", "let u=new URL('https://x.test/a'); u.pathname='/b'; u.pathname"},
  {"headers set get", "let h=new Headers(); h.set('x','y'); h.get('x')"},
  {"formdata append get", "let f=new FormData(); f.append('x','y'); f.get('x')"},
  {"blob size", "new Blob(['abc']).size"},
  {"text decoder", "new TextDecoder().decode(new Uint8Array([97,98]))"},
  {"structured clone object", "structuredClone({x:1}).x"},
  {"atob btoa", "atob(btoa('ab'))"},
  {"performance now type", "typeof performance.now()"},
  {"crypto random uuid type", "typeof crypto.randomUUID()"},
  {"abort controller", "let c=new AbortController(); c.abort(); c.signal.aborted"},
  {"event target", "let e=new EventTarget(); typeof e.addEventListener"},
  {"urlsearchparams", "let p=new URLSearchParams('a=1'); p.get('a')"},
  {"regexp match all count", "Array.from('aba'.matchAll(/a/g)).length"},
  {"regexp sticky", "let r=/a/y; r.test('a') && r.lastIndex"},
  {"unicode normalize", "'é'.normalize('NFC')"},
  {"array find index", "[1,2,3].findIndex(x=>x>1)"},
  {"array find last", "[1,2,3].findLast(x=>x<3)"},
  {"array find last index", "[1,2,3].findLastIndex(x=>x<3)"},
  {"object groupby type", "typeof Object.groupBy"},
  {"bitwise and", "(5 & 3)"},
  {"bitwise or", "(5 | 2)"},
  {"bitwise xor", "(5 ^ 1)"},
  {"bitwise not", "~5"},
  {"left shift", "1 << 3"},
  {"signed right shift", "-8 >> 1"},
  {"unsigned right shift", "-1 >>> 0"},
  {"exponentiation", "2 ** 5"},
  {"negative exponent", "2 ** -1"},
  {"nan inequality", "NaN !== NaN"},
  {"object to primitive plus", "let o={valueOf(){return 2}}; o + 3"},
  {"object to string concat", "let o={toString(){return 'x'}}; o + 'y'"},
  {"loose equality", "0 == false"},
  {"strict equality", "0 === false"},
  {"relational string", "'b' > 'a'"},
  {"ternary nested", "let x=1; x ? (x+1) : 0"},
  {"comma expression", "let x=1; (x=2, x+1)"},
  {"sequence in arg", "function f(x){return x}; f((1,2))"},
  {"short circuit and", "let x=0; false && (x=1); x"},
  {"short circuit or", "let x=0; true || (x=1); x"},
  {"nullish no eval rhs", "let x=0; let y=1 ?? (x=2); x+y"},
  {"optional delete", "let o=null; delete o?.x"},
  {"typeof undeclared", "typeof definitelyMissing"},
  {"void expr", "void (1+2)"},
  {"function var scope", "function f(){ if(true){var x=1} return x } f()"},
  {"block let shadow", "let x=1; { let x=2; } x"},
  {"closure loop let", "let fs=[]; for (let i=0;i<3;i++) fs.push(()=>i); fs[1]()"},
  {"closure loop var", "let fs=[]; for (var i=0;i<3;i++) fs.push(()=>i); fs[1]()"},
  {"for continue", "let s=0; for(let i=0;i<5;i++){ if(i%2) continue; s+=i } s"},
  {"while break", "let i=0; while(true){ if(i===3) break; i++ } i"},
  {"label continue",
   "let s=0; outer: for(let i=0;i<2;i++){ for(let j=0;j<2;j++){ continue outer; s++ }} s"},
  {"switch default middle", "let x=0; switch(3){case 1:x=1;break;default:x=2;case 3:x+=3} x"},
  {"nested function hoist", "function f(){ return g(); function g(){return 4} } f()"},
  {"error constructor name", "new TypeError('x').name"},
  {"aggregate error type", "typeof AggregateError"},
  {"symbol iterator type", "typeof Symbol.iterator"},
  {"promise resolve await primitive",
   "async function f(){ return await Promise.resolve(9) } f()"},
  {"async arrow await promise", "let f=async()=>await Promise.resolve(10); f()"},
  {"class computed getter", "let k='x'; class A { get [k](){return 1} } new A().x"},
  {"class computed setter",
   "let k='x'; class A { set [k](v){this.y=v} } let a=new A(); a.x=2; a.y"},
  {"class static computed method", "let k='m'; class A { static [k](){return 3} } A.m()"},
  {"class static computed field", "let k='x'; class A { static [k]=4 } A.x"},
  {"class private getter", "class A { get #x(){return 5} m(){return this.#x} } new A().m()"},
  {"class private setter",
   "class A { #y=0; set #x(v){this.#y=v} m(){this.#x=6; return this.#y} } new A().m()"},
  {"class static private getter",
   "class A { static get #x(){return 7} static m(){return this.#x} } A.m()"},
  {"derived super property read",
   "class A { constructor(){this.x=1} } class B extends A { m(){return super.x} } new B().m()"},
  {"derived super getter",
   "class A { get x(){return 2} } class B extends A { m(){return super.x} } new B().m()"},
  {"object proto literal", "let p={x:1}; let o={__proto__:p}; o.x"},
  {"object computed getter", "let k='x'; let o={ get [k](){return 8} }; o.x"},
  {"object computed setter", "let k='x'; let o={ set [k](v){this.y=v} }; o.x=9; o.y"},
  {"object method this", "let o={x:2,m(){return this.x}}; let f=o.m; f.call(o)"},
  {"spread set", "[...new Set([1,2])].length"},
  {"object rest symbols", "let s=Symbol('s'); let {[s]:x,...r}={[s]:1,a:2}; r.a+x"},
  {"nested default destructuring", "let {a:{b=3}={}}={}; b"},
  {"destructuring eval name", "let {eval: x}={eval:4}; x"},
  {"catch no binding", "let x=0; try { throw 1 } catch { x=2 } x"},
  {"optional chain call this", "let o={x:2,m(){return this.x}}; o.m?.()"},
  {"optional chain nested missing", "let o={}; o.a?.b?.c === undefined"},
  {"logical and assignment", "let x=1; x &&= 5; x"},
  {"logical nullish object prop", "let o={}; o.x ??= 4; o.x"},
  {"logical or object prop", "let o={x:0}; o.x ||= 4; o.x"},
  {"logical and object prop", "let o={x:1}; o.x &&= 4; o.x"},
  {"indirect eval", "let e=eval; e('1+2')"},
  {"arguments length", "function f(){return arguments.length} f(1,2,3)"},
  {"arguments callee type", "function f(){return typeof arguments.callee} f()"},
  {"rest and arguments", "function f(...xs){return arguments.length+xs.length} f(1,2)"},
  {"default param arguments", "function f(x=arguments.length){return x} f()"},
  {"named function expression", "let f=function g(){return typeof g}; f()"},
  {"recursive named function expression", "let f=function g(n){return n?g(n-1)+1:0}; f(3)"},
  {"new target function", "function F(){return new.target===F}; new F()"},
  {"class new target", "class A { constructor(){this.v=new.target===A} } new A().v"},
  {"async generator type", "async function* g(){ yield 1 } typeof g"},
  {"array keys iteration", "let s=0; for (let k of [1,2].keys()) s+=k; s"},
  {"array values iteration", "let s=0; for (let v of [1,2].values()) s+=v; s"},
  {"array entries iteration", "let s=0; for (let [k,v] of [1,2].entries()) s+=k+v; s"},
  {"array to sorted type", "typeof [2,1].toSorted"},
  {"array length truncate", "let a=[1,2,3]; a.length=1; a.length+a[0]"},
  {"array length extend", "let a=[1]; a.length=3; a[2] === undefined && a.length"},
  {"object assign multiple", "let o=Object.assign({a:1},{b:2},{c:3}); o.a+o.b+o.c"},
  {"object property names", "Object.getOwnPropertyNames({a:1,b:2}).length"},
  {"object symbols", "let s=Symbol('s'); Object.getOwnPropertySymbols({[s]:1}).length"},
  {"object is", "Object.is(NaN, NaN)"},
  {"object is negative zero", "Object.is(-0, 0)"},
  {"map clear", "let m=new Map([[1,2]]); m.clear(); m.size"},
  {"set clear", "let s=new Set([1]); s.clear(); s.size"},
  {"set values first", "let it=new Set([3]).values(); it.next().value"},
  {"weakmap has", "let k={}; let m=new WeakMap([[k,1]]); m.has(k)"},
  {"weakmap delete", "let k={}; let m=new WeakMap([[k,1]]); m.delete(k); m.has(k)"},
  {"weakset delete", "let k={}; let s=new WeakSet([k]); s.delete(k); s.has(k)"},
  {"typed array map", "let a=new Uint8Array([1,2]); a.map(x=>x+1)[1]"},
  {"typed array filter", "let a=new Uint8Array([1,2,3]); a.filter(x=>x>1).length"},
  {"typed array reduce", "let a=new Uint8Array([1,2,3]); a.reduce((a,b)=>a+b,0)"},
  {"typed array set", "let a=new Uint8Array(2); a.set([5],1); a[1]"},
  {"typed array subarray", "let a=new Uint8Array([1,2,3]); a.subarray(1).length"},
  {"float32 rounding", "let a=new Float32Array(1); a[0]=1.5; a[0]"},
  {"int8 overflow", "let a=new Int8Array(1); a[0]=129; a[0]"},
  {"data view byte length", "let b=new ArrayBuffer(4); let v=new DataView(b); v.byteLength"},
  {"urlsearchparams append", "let p=new URLSearchParams(); p.append('a','1'); p.toString()"},
  {"headers has", "let h=new Headers({'x':'y'}); h.has('x')"},
  {"headers delete", "let h=new Headers({'x':'y'}); h.delete('x'); h.has('x')"},
  {"text encoder empty", "new TextEncoder().encode('').length"},
  {"blob text type", "typeof new Blob(['x']).text"},
  {"custom event detail", "new CustomEvent('x',{detail:3}).detail"},
  {"abort signal reason type", "let c=new AbortController(); c.abort('x'); c.signal.aborted"},
  {"performance time origin type", "typeof performance.timeOrigin"},
  {"crypto get random length", "let a=new Uint8Array(2); crypto.getRandomValues(a).length"},
  {"string replace all regex global", "'aaa'.replaceAll(/a/g,'b')"},
  {"bigint to string", "(10n).toString()"},
  {"symbol description", "Symbol('x').description"},
  {"symbol to string", "Symbol('x').toString()"},
  {"symbol for equality", "Symbol.for('x') === Symbol.for('x')"},
  {"regexp source", "/a+/.source"},
  {"regexp global flag", "/a/g.global"},
  {"regexp ignorecase flag", "/a/i.ignoreCase"},
  {"regexp multiline flag", "/a/m.multiline"},
  {"regexp exec index", "/b/.exec('abc').index"},
  {"regexp named groups undefined type", "typeof /(?<x>a)/.exec('a').groups"},
  {"string search", "'abc'.search(/b/)"},
  {"string match regex", "'abc'.match(/b/)[0]"},
  {"string char at", "'abc'.charAt(1)"},
  {"string substring", "'abc'.substring(1,3)"},
  {"string substr type", "typeof 'abc'.substr"},
  {"string concat", "'a'.concat('b','c')"},
  {"string includes from", "'abcabc'.includes('a',1)"},
  {"string indexof", "'abc'.indexOf('b')"},
  {"string lastindexof", "'abca'.lastIndexOf('a')"},
  {"string locale compare type", "typeof 'a'.localeCompare('b')"},
  {"number to string radix", "(10).toString(16)"},
  {"number to precision", "(1.23).toPrecision(2)"},
  {"number finite global", "isFinite(1/0)"},
  {"global isnan", "isNaN(NaN)"},
  {"math imul", "Math.imul(2,3)"},
  {"math fround", "typeof Math.fround(1.5)"},
  {"math random type", "typeof Math.random()"},
  {"math abs negative zero", "Object.is(Math.abs(-0), 0)"},
  {"json stringify array", "JSON.stringify([1,2])"},
  {"json stringify replacer array", "JSON.stringify({a:1,b:2}, ['b'])"},
  {"json parse array", "JSON.parse('[1,2]').length"},
  {"object define properties",
   "let o={}; Object.defineProperties(o,{x:{value:1},y:{value:2}}); o.x+o.y"},
  {"object entries map", "Object.entries({a:1})[0][0]"},
  {"object values first", "Object.values({a:1})[0]"},
  {"object keys symbol ignored", "let s=Symbol('s'); Object.keys({[s]:1,a:2}).length"}
]

results =
  Enum.map(cases, fn {name, source} -> QuickBEAM.VM.CompilerAudit.run_case(name, source) end)

summary = QuickBEAM.VM.CompilerAudit.summary(results)
failures = summary.fallbacks + summary.crashes + summary.mismatches + summary.input_errors

IO.puts(
  "compiler_semantic_cases=#{summary.cases} compiler_semantic_compiled=#{summary.compiled} compiler_semantic_failures=#{failures} compiler_semantic_fallbacks=#{summary.fallbacks} compiler_semantic_crashes=#{summary.crashes} compiler_semantic_mismatches=#{summary.mismatches} compiler_semantic_input_errors=#{summary.input_errors}"
)

for result <- results, result.status != :compiled do
  IO.puts("COMPILER_SEMANTIC_#{String.upcase(to_string(result.status))} #{result.name}")
  IO.puts("  source=#{result.source}")
  IO.puts("  interpreter=#{inspect(result.interpreter)}")
  IO.puts("  compiler=#{inspect(result.compiler)}")
end

IO.puts("METRIC compiler_semantic_cases=#{summary.cases}")
IO.puts("METRIC compiler_semantic_compiled=#{summary.compiled}")
IO.puts("METRIC compiler_semantic_failures=#{failures}")
IO.puts("METRIC compiler_semantic_fallbacks=#{summary.fallbacks}")
IO.puts("METRIC compiler_semantic_crashes=#{summary.crashes}")
IO.puts("METRIC compiler_semantic_mismatches=#{summary.mismatches}")
IO.puts("METRIC compiler_semantic_input_errors=#{summary.input_errors}")
