Mix.Task.run("app.start")

Code.require_file("../test/support/vm_compiler_audit.ex", __DIR__)

cases = [
  {"derived constructor primitive return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return 1 } } new B()"},
  {"with property assignment", "let o={x:1}; with(o){ x=2; } o.x"},
  {"with missing global assignment", "var x=1; let o={}; with(o){ x=2; } x"},
  {"with property update", "let o={x:1}; with(o){ x++; } o.x"},
  {"with unscopables fallback",
   "var x=1; let o={x:2, [Symbol.unscopables]: {x:true}}; with(o){ x=3; } [x,o.x]"},
  {"async function invocation", "async function f(){ return 1 } f()"},
  {"generator next value", "function* g(){ yield 1; return 2 } let it=g(); it.next().value"},
  {"dynamic import rejection", "import('x')"},
  {"derived constructor undefined return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return undefined } } new B().a"},
  {"derived constructor object return",
   "class A { constructor(){ this.a = 1 } } class B extends A { constructor(){ super(); return {b:2} } } new B().b"},
  {"with captured assignment",
   "var out; function f(){ let x=1; function g(){ let o={}; with(o){ x=2 } return x } return g() } f()"},
  {"with local fallback read", "let o={}; let x=1; with(o){ x }"},
  {"with delete property", "let o={x:1}; with(o){ delete x; } 'x' in o"},
  {"async await value", "async function f(){ return await 2 } f()"},
  {"async await resolved promise", "async function f(){ return await Promise.resolve(3) } f()"},
  {"generator two next values",
   "function* g(){ yield 1; yield 2; return 3 } let it=g(); it.next().value + it.next().value"},
  {"generator return value",
   "function* g(){ yield 1; return 3 } let it=g(); it.next(); it.next().value"},
  {"async caught throw", "async function f(){ try { throw 4 } catch(e) { return e } } f()"},
  {"with fallback method call", "function m(){return 3}; let o={}; with(o){ m() }"},
  {"with property method call", "let o={x:2, m(){return this.x}}; with(o){ m() }"},
  {"with property function this", "let o={x:3, m:function(){return this.x}}; with(o){ m() }"},
  {"with property arrow call", "let o={x:4, m:()=>5}; with(o){ m() }"},
  {"with method arguments", "let o={m(a,b){return a+b}}; with(o){ m(2,3) }"},
  {"with method update", "let o={x:1, inc(){this.x++; return this.x}}; with(o){ inc() }"},
  {"with missing property delete", "let o={}; with(o){ delete x }"},
  {"with captured update",
   "function f(){ let x=1; function g(){ let o={}; with(o){ x++ } return x } return g() } f()"},
  {"with captured unscopables fallback",
   "function f(){ let x=1; function g(){ let o={x:2,[Symbol.unscopables]:{x:true}}; with(o){ x=3 } return [x,o.x] } return g() } f()"},
  {"async await chained promise",
   "async function f(){ return await Promise.resolve(1).then(function(v){ return v+1 }) } f()"},
  {"async nested await",
   "async function f(){ return await Promise.resolve(await Promise.resolve(4)) } f()"},
  {"async rejection catch",
   "async function f(){ return await Promise.reject('err').catch(function(e){ return e + '!' }) } f()"},
  {"generator third next value",
   "function* g(){ yield 1; yield 2; return 3 } let it=g(); it.next(); it.next(); it.next().value"},
  {"generator return method", "function* g(){ yield 1; yield 2 } let it=g(); it.return(9).value"},
  {"derived constructor new target",
   "class A { constructor(){ this.v = new.target.name } } class B extends A { constructor(){ super() } } new B().v"},
  {"computed class value invoked", "let o={ [class C{}]: 1 }; 1"},
  {"custom iterator loop value",
   "let it={ [Symbol.iterator](){ return { i:0, next(){ return this.i++ < 1 ? {value:7, done:false} : {done:true}; } } } }; let s=0; for (let x of it) s+=x; s"},
  {"with fallback delete global", "var x=1; let o={}; with(o){ delete x } x"},
  {"with unscopables read fallback",
   "var x=1; let o={x:2,[Symbol.unscopables]:{x:true}}; with(o){ x }"},
  {"async multiple awaits sum",
   "async function f(){ let a=await 1; let b=await 2; return a+b } f()"},
  {"async promise all length",
   "async function f(){ let r = await Promise.all([Promise.resolve(1), Promise.resolve(2)]); return r.length } f()"},
  {"generator next done flag", "function* g(){ yield 1 } let it=g(); it.next(); it.next().done"},
  {"generator send ignored first",
   "function* g(){ let x = yield 1; return x } let it=g(); it.next(5).value"},
  {"generator send second",
   "function* g(){ let x = yield 1; return x } let it=g(); it.next(); it.next(7).value"},
  {"derived super argument",
   "class A { constructor(x){ this.x=x } } class B extends A { constructor(){ super(5) } } new B().x"},
  {"super method call",
   "class A { m(){ return 1 } } class B extends A { m(){ return super.m()+1 } } new B().m()"},
  {"private field method", "class A { #x=1; m(){ return this.#x } } new A().m()"},
  {"array destructuring default", "let [a=3] = []; a"},
  {"object spread override", "let o={...{x:1}, x:2}; o.x"},
  {"optional chain method", "let o={x:1,m(){return this.x}}; o?.m()"},
  {"nullish assignment", "let x=null; x ??= 3; x"},
  {"logical assignment", "let x=0; x ||= 4; x"},
  {"regexp exec group", "/(a+)/.exec('aa')[1]"},
  {"typed array value", "let a=new Uint8Array(2); a[0]=255; a[0]"},
  {"map set get", "let m=new Map(); m.set('x', 2); m.get('x')"},
  {"set has", "let s=new Set(); s.add(3); s.has(3)"},
  {"string includes", "'quickbeam'.includes('beam')"},
  {"array map length", "[1,2,3].map(function(x){return x+1}).length"},
  {"array reduce sum", "[1,2,3].reduce(function(a,b){return a+b},0)"},
  {"object keys length", "Object.keys({a:1,b:2}).length"},
  {"json stringify object", "JSON.stringify({a:1})"},
  {"date now type", "typeof Date.now()"},
  {"bigint addition", "1n + 2n"},
  {"bigint compare", "2n > 1n"},
  {"symbol property", "let s=Symbol('x'); let o={[s]:3}; o[s]"},
  {"class static field", "class A { static x=3; static m(){return this.x} } A.m()"},
  {"private method", "class A { #m(){return 4} m(){return this.#m()} } new A().m()"},
  {"static super method",
   "class A { static m(){return 1} } class B extends A { static m(){return super.m()+2} } B.m()"},
  {"try finally return override", "function f(){ try { return 1 } finally { return 2 } } f()"},
  {"catch binding", "try { throw 5 } catch(e) { e+1 }"},
  {"for in keys", "let s=''; for (let k in {a:1,b:2}) s+=k; s.length"},
  {"for of destructuring", "let s=0; for (let [x] of [[1],[2]]) s+=x; s"},
  {"spread constructor", "function A(a,b){this.v=a+b}; new A(...[1,2]).v"},
  {"rest parameter", "function f(...xs){ return xs.length + xs[0] } f(3,4)"},
  {"array filter join", "[1,2,3,4].filter(function(x){return x%2===0}).join(',')"},
  {"array find", "[1,2,3].find(function(x){return x>1})"},
  {"array includes", "[1,2,3].includes(2)"},
  {"string replace", "'a-b'.replace('-', '+')"},
  {"string split length", "'a,b,c'.split(',').length"},
  {"number to fixed", "(1.25).toFixed(1)"},
  {"math max", "Math.max(1,5,3)"},
  {"object assign", "let o=Object.assign({a:1},{b:2}); o.b"},
  {"object define property", "let o={}; Object.defineProperty(o,'x',{value:4}); o.x"},
  {"property descriptor", "let o={x:1}; Object.getOwnPropertyDescriptor(o,'x').value"},
  {"set size", "let s=new Set([1,2,2]); s.size"},
  {"map size", "let m=new Map([['a',1],['b',2]]); m.size"},
  {"weakmap basic", "let k={}; let m=new WeakMap(); m.set(k,3); m.get(k)"},
  {"uint16 overflow", "let a=new Uint16Array(1); a[0]=65537; a[0]"},
  {"text encoder length", "new TextEncoder().encode('abc').length"},
  {"url pathname", "new URL('https://x.test/a?b=1').pathname"},
  {"regexp replace capture", "'abc'.replace(/(b)/, '[$1]')"},
  {"class getter setter",
   "class A { set x(v){this.v=v} get x(){return this.v} } let a=new A(); a.x=5; a.x"},
  {"static block", "class A { static { this.x=6 } } A.x"},
  {"private static field", "class A { static #x=7; static m(){return this.#x} } A.m()"},
  {"optional call missing", "let f=null; f?.() === undefined"},
  {"optional chain element", "let o={a:[3]}; o?.a?.[0]"},
  {"nested destructuring", "let {a:{b}}={a:{b:8}}; b"},
  {"rest object", "let {a,...r}={a:1,b:2}; r.b"},
  {"spread array", "let a=[1,...[2,3]]; a.length"},
  {"default param closure", "function f(x=3){return function(){return x}} f()()"},
  {"arrow this lexical", "let o={x:4,m(){let f=()=>this.x; return f()}}; o.m()"},
  {"eval local", "function f(){ var x=1; eval('x=2'); return x } f()"},
  {"direct eval expr", "eval('1+2')"},
  {"function bind", "function f(a,b){return a+b}; f.bind(null,2)(3)"},
  {"call apply", "function f(a,b){return a+b}; f.apply(null,[2,4])"},
  {"proxy get", "let p=new Proxy({x:1},{get(t,k){return t[k]+1}}); p.x"},
  {"proxy set", "let o={}; let p=new Proxy(o,{set(t,k,v){t[k]=v+1; return true}}); p.x=2; o.x"},
  {"reflect get", "Reflect.get({x:2}, 'x')"},
  {"reflect set", "let o={}; Reflect.set(o,'x',3); o.x"},
  {"array from set", "Array.from(new Set([1,2])).length"},
  {"array flat", "[1,[2,[3]]].flat(2).length"},
  {"array flatmap", "[1,2].flatMap(function(x){return [x,x]}).length"},
  {"string match", "'abc'.match(/b/)[0]"},
  {"template tag", "function tag(s,v){return s[0]+v}; tag`x${3}`"},
  {"computed property assignment", "let k='x'; let o={}; o[k]=4; o.x"},
  {"super setter",
   "class A { set x(v){this.y=v} } class B extends A { m(){ super.x=5; return this.y } } new B().m()"},
  {"static super setter",
   "class A { static set x(v){this.y=v} } class B extends A { static m(){ super.x=6; return this.y } } B.m()"},
  {"private setter",
   "class A { #x=0; set x(v){this.#x=v} get x(){return this.#x} } let a=new A(); a.x=7; a.x"},
  {"class field arrow", "class A { x=1; m=()=>this.x } new A().m()"},
  {"static private method",
   "class A { static #m(){return 8} static m(){return this.#m()} } A.m()"},
  {"object entries", "Object.entries({a:1,b:2}).length"},
  {"object from entries", "Object.fromEntries([['x',1]]).x"},
  {"assign accessor", "let o={set x(v){this.y=v}}; Object.assign(o,{x:2}); o.y"},
  {"intl unavailable type", "typeof Intl"},
  {"parse int", "parseInt('10', 10)"},
  {"is finite", "Number.isFinite(3)"},
  {"nan compare", "Number.isNaN(NaN)"},
  {"error message", "try { throw new Error('boom') } catch(e) { e.message }"},
  {"finally mutation", "let x=1; try { x=2 } finally { x=3 } x"},
  {"switch fallthrough", "let x=0; switch(1){case 1:x++; case 2:x++;} x"},
  {"labeled break", "let x=0; outer: while(true){ x=1; break outer; x=2 } x"},
  {"do while", "let x=0; do { x++ } while(x<3); x"},
  {"uint8 clamped", "let a=new Uint8ClampedArray(1); a[0]=300; a[0]"},
  {"array buffer byte length", "new ArrayBuffer(8).byteLength"},
  {"typed array slice", "let a=new Uint8Array([1,2,3]); a.slice(1)[0]"},
  {"map iteration sum", "let m=new Map([[1,2],[3,4]]); let s=0; for (let [k,v] of m) s+=k+v; s"},
  {"set iteration sum", "let s=new Set([1,2]); let n=0; for (let x of s) n+=x; n"},
  {"string iterator", "let s=''; for (let c of 'ab') s+=c; s"},
  {"object values length", "Object.values({a:1,b:2}).length"},
  {"object hasown", "Object.hasOwn({x:1}, 'x')"},
  {"object create proto", "let p={x:1}; let o=Object.create(p); o.x"},
  {"property getter descriptor",
   "let o={get x(){return 2}}; Object.getOwnPropertyDescriptor(o,'x').get.call(o)"},
  {"define getter", "let o={}; Object.defineProperty(o,'x',{get(){return 4}}); o.x"},
  {"delete property result", "let o={x:1}; delete o.x"},
  {"in prototype", "let p={x:1}; let o=Object.create(p); 'x' in o"},
  {"instanceof class", "class A{}; new A() instanceof A"},
  {"new bound function", "function A(x){this.x=x}; let B=A.bind(null,5); new B().x"},
  {"symbol for key", "Symbol.keyFor(Symbol.for('x'))"},
  {"global this math", "globalThis.Math === Math"},
  {"json parse", "JSON.parse('{\"x\":2}').x"},
  {"json parse reviver", "JSON.parse('{\"x\":2}', function(k,v){return k==='x'?v+1:v}).x"},
  {"regexp test global", "let r=/a/g; r.test('a') && r.lastIndex"},
  {"regexp flags", "/a/gi.flags"},
  {"string pad", "'x'.padStart(3,'0')"},
  {"string trim", "' x '.trim()"},
  {"number parse float", "Number.parseFloat('1.5')"},
  {"math trunc", "Math.trunc(1.9)"},
  {"array sort", "[3,1,2].sort()[0]"},
  {"array every", "[1,2,3].every(x=>x>0)"},
  {"array some", "[1,2,3].some(x=>x>2)"},
  {"array fill", "let a=[0,0,0]; a.fill(5,1); a[1]"},
  {"array copyWithin", "let a=[1,2,3]; a.copyWithin(1,0,1); a[1]"},
  {"array at", "[1,2,3].at(-1)"},
  {"string startswith", "'quickbeam'.startsWith('quick')"},
  {"string endswith", "'quickbeam'.endsWith('beam')"},
  {"string repeat", "'ab'.repeat(3)"},
  {"string code point", "'😀'.codePointAt(0)"},
  {"string from code point", "String.fromCodePoint(65)"},
  {"array reverse", "let a=[1,2,3]; a.reverse()[0]"},
  {"array shift", "let a=[1,2]; a.shift()+a.length"},
  {"array unshift", "let a=[2]; a.unshift(1); a[0]+a.length"},
  {"array push pop", "let a=[]; a.push(1,2); a.pop()+a.length"},
  {"array splice", "let a=[1,2,3]; a.splice(1,1,4); a[1]"},
  {"array concat", "[1].concat([2,3]).length"},
  {"array lastindexof", "[1,2,1].lastIndexOf(1)"},
  {"array join sparse", "[1,,3].join('-')"},
  {"math sign", "Math.sign(-3)"},
  {"math hypot", "Math.hypot(3,4)"},
  {"math clz32", "Math.clz32(1)"},
  {"number is integer", "Number.isInteger(3.0)"},
  {"number epsilon type", "typeof Number.EPSILON"},
  {"parse float global", "parseFloat('2.5x')"},
  {"weakset has", "let k={}; let s=new WeakSet(); s.add(k); s.has(k)"},
  {"map delete", "let m=new Map([[1,2]]); m.delete(1) && m.size"},
  {"set delete", "let s=new Set([1]); s.delete(1) && s.size"},
  {"map forEach", "let m=new Map([[1,2],[3,4]]); let s=0; m.forEach((v,k)=>s+=v+k); s"},
  {"object get prototype", "let p={}; let o=Object.create(p); Object.getPrototypeOf(o) === p"},
  {"object set prototype", "let p={x:1}; let o={}; Object.setPrototypeOf(o,p); o.x"},
  {"reflect has", "Reflect.has({x:1}, 'x')"},
  {"proxy has", "let p=new Proxy({}, {has(){return true}}); 'x' in p"},
  {"proxy ownkeys",
   "let p=new Proxy({}, {ownKeys(){return ['x']}, getOwnPropertyDescriptor(){return {configurable:true, enumerable:true}}}); Object.keys(p)[0]"},
  {"destructuring rest array", "let [a,...r]=[1,2,3]; r.length+a"},
  {"parameter destructuring", "function f({x}, [y]){return x+y}; f({x:1}, [2])"},
  {"computed object method", "let k='m'; let o={ [k](){return 6} }; o.m()"},
  {"async arrow", "let f=async x=>await x+1; f(2)"},
  {"class extends expression", "let B=class {m(){return 1}}; class A extends B {}; new A().m()"},
  {"static block private",
   "class A { static #x; static { this.#x=4 } static m(){return this.#x} } A.m()"},
  {"private in true", "class A { #x; has(o){return #x in o} } let a=new A(); a.has(a)"},
  {"private in false", "class A { #x; has(o){return #x in o} } new A().has({})"},
  {"try catch finally", "let x=0; try { throw 1 } catch(e){ x=e } finally { x+=2 } x"},
  {"nested switch", "let x=0; switch(2){case 1:x=1;break;case 2:switch(1){case 1:x=3}} x"},
  {"date full year", "new Date(0).getFullYear()"},
  {"date utc year", "new Date(Date.UTC(2020,0,1)).getUTCFullYear()"},
  {"date parse type", "typeof Date.parse('2020-01-01T00:00:00Z')"},
  {"date to json type", "typeof new Date(0).toJSON()"},
  {"promise all values",
   "async function f(){ let r=await Promise.all([1, Promise.resolve(2)]); return r[0]+r[1] } f()"},
  {"promise race value",
   "async function f(){ return await Promise.race([Promise.resolve(3)]) } f()"},
  {"promise all settled length",
   "async function f(){ let r=await Promise.allSettled([Promise.resolve(1)]); return r.length } f()"},
  {"async finally return", "async function f(){ try { return 1 } finally { } } f()"},
  {"async finally override", "async function f(){ try { return 1 } finally { return 2 } } f()"},
  {"async catch finally",
   "async function f(){ try { throw 1 } catch(e){ return e+1 } finally {} } f()"},
  {"generator finally return",
   "function* g(){ try { yield 1 } finally { return 4 } } let it=g(); it.next(); it.next().value"},
  {"generator yield in finally",
   "function* g(){ try { yield 1 } finally { yield 2 } } let it=g(); it.next(); it.next().value"},
  {"url search params get", "new URL('https://x.test/?a=1').searchParams.get('a')"},
  {"url href set", "let u=new URL('https://x.test/a'); u.pathname='/b'; u.pathname"},
  {"headers set get", "let h=new Headers(); h.set('x','y'); h.get('x')"},
  {"formdata append get", "let f=new FormData(); f.append('x','y'); f.get('x')"},
  {"blob size", "new Blob(['abc']).size"},
  {"text decoder", "new TextDecoder().decode(new Uint8Array([97,98]))"},
  {"structured clone object", "structuredClone({x:1}).x"},
  {"atob btoa", "atob(btoa('ab'))"},
  {"performance now type", "typeof performance.now()"},
  {"crypto random uuid type", "typeof crypto.randomUUID()"},
  {"abort controller", "let c=new AbortController(); c.abort(); c.signal.aborted"},
  {"event target", "let e=new EventTarget(); typeof e.addEventListener"},
  {"urlsearchparams", "let p=new URLSearchParams('a=1'); p.get('a')"},
  {"regexp match all count", "Array.from('aba'.matchAll(/a/g)).length"},
  {"regexp sticky", "let r=/a/y; r.test('a') && r.lastIndex"},
  {"unicode normalize", "'é'.normalize('NFC')"},
  {"array find index", "[1,2,3].findIndex(x=>x>1)"},
  {"array find last", "[1,2,3].findLast(x=>x<3)"},
  {"array find last index", "[1,2,3].findLastIndex(x=>x<3)"},
  {"object groupby type", "typeof Object.groupBy"},
  {"bitwise and", "(5 & 3)"},
  {"bitwise or", "(5 | 2)"},
  {"bitwise xor", "(5 ^ 1)"},
  {"bitwise not", "~5"},
  {"left shift", "1 << 3"},
  {"signed right shift", "-8 >> 1"},
  {"unsigned right shift", "-1 >>> 0"},
  {"exponentiation", "2 ** 5"},
  {"negative exponent", "2 ** -1"},
  {"nan inequality", "NaN !== NaN"},
  {"object to primitive plus", "let o={valueOf(){return 2}}; o + 3"},
  {"object to string concat", "let o={toString(){return 'x'}}; o + 'y'"},
  {"loose equality", "0 == false"},
  {"strict equality", "0 === false"},
  {"relational string", "'b' > 'a'"},
  {"ternary nested", "let x=1; x ? (x+1) : 0"},
  {"comma expression", "let x=1; (x=2, x+1)"},
  {"sequence in arg", "function f(x){return x}; f((1,2))"},
  {"short circuit and", "let x=0; false && (x=1); x"},
  {"short circuit or", "let x=0; true || (x=1); x"},
  {"nullish no eval rhs", "let x=0; let y=1 ?? (x=2); x+y"},
  {"optional delete", "let o=null; delete o?.x"},
  {"typeof undeclared", "typeof definitelyMissing"},
  {"void expr", "void (1+2)"},
  {"function var scope", "function f(){ if(true){var x=1} return x } f()"},
  {"block let shadow", "let x=1; { let x=2; } x"},
  {"closure loop let", "let fs=[]; for (let i=0;i<3;i++) fs.push(()=>i); fs[1]()"},
  {"closure loop var", "let fs=[]; for (var i=0;i<3;i++) fs.push(()=>i); fs[1]()"},
  {"for continue", "let s=0; for(let i=0;i<5;i++){ if(i%2) continue; s+=i } s"},
  {"while break", "let i=0; while(true){ if(i===3) break; i++ } i"},
  {"label continue",
   "let s=0; outer: for(let i=0;i<2;i++){ for(let j=0;j<2;j++){ continue outer; s++ }} s"},
  {"switch default middle", "let x=0; switch(3){case 1:x=1;break;default:x=2;case 3:x+=3} x"},
  {"nested function hoist", "function f(){ return g(); function g(){return 4} } f()"},
  {"error constructor name", "new TypeError('x').name"},
  {"aggregate error type", "typeof AggregateError"},
  {"symbol iterator type", "typeof Symbol.iterator"},
  {"promise resolve await primitive",
   "async function f(){ return await Promise.resolve(9) } f()"},
  {"async arrow await promise", "let f=async()=>await Promise.resolve(10); f()"},
  {"class computed getter", "let k='x'; class A { get [k](){return 1} } new A().x"},
  {"class computed setter",
   "let k='x'; class A { set [k](v){this.y=v} } let a=new A(); a.x=2; a.y"},
  {"class static computed method", "let k='m'; class A { static [k](){return 3} } A.m()"},
  {"class static computed field", "let k='x'; class A { static [k]=4 } A.x"},
  {"class private getter", "class A { get #x(){return 5} m(){return this.#x} } new A().m()"},
  {"class private setter",
   "class A { #y=0; set #x(v){this.#y=v} m(){this.#x=6; return this.#y} } new A().m()"},
  {"class static private getter",
   "class A { static get #x(){return 7} static m(){return this.#x} } A.m()"},
  {"derived super property read",
   "class A { constructor(){this.x=1} } class B extends A { m(){return super.x} } new B().m()"},
  {"derived super getter",
   "class A { get x(){return 2} } class B extends A { m(){return super.x} } new B().m()"},
  {"object proto literal", "let p={x:1}; let o={__proto__:p}; o.x"},
  {"object computed getter", "let k='x'; let o={ get [k](){return 8} }; o.x"},
  {"object computed setter", "let k='x'; let o={ set [k](v){this.y=v} }; o.x=9; o.y"},
  {"object method this", "let o={x:2,m(){return this.x}}; let f=o.m; f.call(o)"},
  {"spread set", "[...new Set([1,2])].length"},
  {"object rest symbols", "let s=Symbol('s'); let {[s]:x,...r}={[s]:1,a:2}; r.a+x"},
  {"nested default destructuring", "let {a:{b=3}={}}={}; b"},
  {"destructuring eval name", "let {eval: x}={eval:4}; x"},
  {"catch no binding", "let x=0; try { throw 1 } catch { x=2 } x"},
  {"optional chain call this", "let o={x:2,m(){return this.x}}; o.m?.()"},
  {"optional chain nested missing", "let o={}; o.a?.b?.c === undefined"},
  {"logical and assignment", "let x=1; x &&= 5; x"},
  {"logical nullish object prop", "let o={}; o.x ??= 4; o.x"},
  {"logical or object prop", "let o={x:0}; o.x ||= 4; o.x"},
  {"logical and object prop", "let o={x:1}; o.x &&= 4; o.x"},
  {"indirect eval", "let e=eval; e('1+2')"},
  {"arguments length", "function f(){return arguments.length} f(1,2,3)"},
  {"arguments callee type", "function f(){return typeof arguments.callee} f()"},
  {"rest and arguments", "function f(...xs){return arguments.length+xs.length} f(1,2)"},
  {"default param arguments", "function f(x=arguments.length){return x} f()"},
  {"named function expression", "let f=function g(){return typeof g}; f()"},
  {"recursive named function expression", "let f=function g(n){return n?g(n-1)+1:0}; f(3)"},
  {"new target function", "function F(){return new.target===F}; new F()"},
  {"class new target", "class A { constructor(){this.v=new.target===A} } new A().v"},
  {"async generator type", "async function* g(){ yield 1 } typeof g"},
  {"array keys iteration", "let s=0; for (let k of [1,2].keys()) s+=k; s"},
  {"array values iteration", "let s=0; for (let v of [1,2].values()) s+=v; s"},
  {"array entries iteration", "let s=0; for (let [k,v] of [1,2].entries()) s+=k+v; s"},
  {"array to sorted type", "typeof [2,1].toSorted"},
  {"array length truncate", "let a=[1,2,3]; a.length=1; a.length+a[0]"},
  {"array length extend", "let a=[1]; a.length=3; a[2] === undefined && a.length"},
  {"object assign multiple", "let o=Object.assign({a:1},{b:2},{c:3}); o.a+o.b+o.c"},
  {"object property names", "Object.getOwnPropertyNames({a:1,b:2}).length"},
  {"object symbols", "let s=Symbol('s'); Object.getOwnPropertySymbols({[s]:1}).length"},
  {"object is", "Object.is(NaN, NaN)"},
  {"object is negative zero", "Object.is(-0, 0)"},
  {"map clear", "let m=new Map([[1,2]]); m.clear(); m.size"},
  {"set clear", "let s=new Set([1]); s.clear(); s.size"},
  {"set values first", "let it=new Set([3]).values(); it.next().value"},
  {"weakmap has", "let k={}; let m=new WeakMap([[k,1]]); m.has(k)"},
  {"weakmap delete", "let k={}; let m=new WeakMap([[k,1]]); m.delete(k); m.has(k)"},
  {"weakset delete", "let k={}; let s=new WeakSet([k]); s.delete(k); s.has(k)"},
  {"typed array map", "let a=new Uint8Array([1,2]); a.map(x=>x+1)[1]"},
  {"typed array filter", "let a=new Uint8Array([1,2,3]); a.filter(x=>x>1).length"},
  {"typed array reduce", "let a=new Uint8Array([1,2,3]); a.reduce((a,b)=>a+b,0)"},
  {"typed array set", "let a=new Uint8Array(2); a.set([5],1); a[1]"},
  {"typed array subarray", "let a=new Uint8Array([1,2,3]); a.subarray(1).length"},
  {"float32 rounding", "let a=new Float32Array(1); a[0]=1.5; a[0]"},
  {"int8 overflow", "let a=new Int8Array(1); a[0]=129; a[0]"},
  {"data view byte length", "let b=new ArrayBuffer(4); let v=new DataView(b); v.byteLength"},
  {"urlsearchparams append", "let p=new URLSearchParams(); p.append('a','1'); p.toString()"},
  {"headers has", "let h=new Headers({'x':'y'}); h.has('x')"},
  {"headers delete", "let h=new Headers({'x':'y'}); h.delete('x'); h.has('x')"},
  {"text encoder empty", "new TextEncoder().encode('').length"},
  {"blob text type", "typeof new Blob(['x']).text"},
  {"custom event detail", "new CustomEvent('x',{detail:3}).detail"},
  {"abort signal reason type", "let c=new AbortController(); c.abort('x'); c.signal.aborted"},
  {"performance time origin type", "typeof performance.timeOrigin"},
  {"crypto get random length", "let a=new Uint8Array(2); crypto.getRandomValues(a).length"},
  {"string replace all regex global", "'aaa'.replaceAll(/a/g,'b')"},
  {"bigint to string", "(10n).toString()"},
  {"symbol description", "Symbol('x').description"},
  {"symbol to string", "Symbol('x').toString()"},
  {"symbol for equality", "Symbol.for('x') === Symbol.for('x')"},
  {"regexp source", "/a+/.source"},
  {"regexp global flag", "/a/g.global"},
  {"regexp ignorecase flag", "/a/i.ignoreCase"},
  {"regexp multiline flag", "/a/m.multiline"},
  {"regexp exec index", "/b/.exec('abc').index"},
  {"regexp named groups undefined type", "typeof /(?<x>a)/.exec('a').groups"},
  {"string search", "'abc'.search(/b/)"},
  {"string match regex", "'abc'.match(/b/)[0]"},
  {"string char at", "'abc'.charAt(1)"},
  {"string substring", "'abc'.substring(1,3)"},
  {"string substr type", "typeof 'abc'.substr"},
  {"string concat", "'a'.concat('b','c')"},
  {"string includes from", "'abcabc'.includes('a',1)"},
  {"string indexof", "'abc'.indexOf('b')"},
  {"string lastindexof", "'abca'.lastIndexOf('a')"},
  {"string locale compare type", "typeof 'a'.localeCompare('b')"},
  {"number to string radix", "(10).toString(16)"},
  {"number to precision", "(1.23).toPrecision(2)"},
  {"number finite global", "isFinite(1/0)"},
  {"global isnan", "isNaN(NaN)"},
  {"math imul", "Math.imul(2,3)"},
  {"math fround", "typeof Math.fround(1.5)"},
  {"math random type", "typeof Math.random()"},
  {"math abs negative zero", "Object.is(Math.abs(-0), 0)"},
  {"json stringify array", "JSON.stringify([1,2])"},
  {"json stringify replacer array", "JSON.stringify({a:1,b:2}, ['b'])"},
  {"json parse array", "JSON.parse('[1,2]').length"},
  {"object define properties",
   "let o={}; Object.defineProperties(o,{x:{value:1},y:{value:2}}); o.x+o.y"},
  {"object entries map", "Object.entries({a:1})[0][0]"},
  {"object values first", "Object.values({a:1})[0]"},
  {"object keys symbol ignored", "let s=Symbol('s'); Object.keys({[s]:1,a:2}).length"},
  {"range error name", "new RangeError('x').name"},
  {"reference error name", "new ReferenceError('x').name"},
  {"syntax error name", "new SyntaxError('x').name"},
  {"uri error name", "new URIError('x').name"},
  {"eval error name", "new EvalError('x').name"},
  {"error cause", "new Error('x',{cause:3}).cause"},
  {"error stack type", "typeof new Error('x').stack"},
  {"throw catch error instance",
   "try { throw new TypeError('x') } catch(e) { e instanceof TypeError }"},
  {"throw catch custom",
   "class E extends Error{}; try{throw new E('x')}catch(e){e instanceof E}"},
  {"promise finally value",
   "async function f(){ return await Promise.resolve(1).finally(()=>{}) } f()"},
  {"promise finally rejected catch",
   "async function f(){ return await Promise.reject(2).finally(()=>{}).catch(e=>e+1) } f()"},
  {"promise any type", "typeof Promise.any"},
  {"promise resolve thenable",
   "async function f(){ return await Promise.resolve({then(r){r(5)}}) } f()"},
  {"async arrow block", "let f=async x=>{let y=await x; return y+1}; f(3)"},
  {"async nested function",
   "async function f(){ async function g(){return 2}; return await g()+1 } f()"},
  {"class async static method type", "class A { static async m(){return 1} } typeof A.m"},
  {"generator yield object", "function* g(){ yield {x:1} } let it=g(); it.next().value.x"},
  {"generator return done", "function* g(){ return 1 } g().next().done"},
  {"generator throw method type", "function* g(){ yield 1 } typeof g().throw"},
  {"async generator next type", "async function* g(){ yield 1 } typeof g().next"},
  {"for await type only", "async function f(){ for await (let x of [1]) return x } typeof f"},
  {"class field computed this", "class A { x=1; [(()=>'y')()] = this.x+1 } new A().y"},
  {"class static field this", "class A { static x=1; static y=this.x+1 } A.y"},
  {"class static block super",
   "class A { static x=1 } class B extends A { static { this.y=super.x+1 } } B.y"},
  {"private brand inheritance",
   "class A { #x=1; m(){return #x in this} } class B extends A{}; new B().m()"},
  {"private field inheritance",
   "class A { #x=1; m(){return this.#x} } class B extends A{}; new B().m()"},
  {"super constructor return object",
   "class A { constructor(){return {x:1}} } class B extends A{}; new B().x"},
  {"derived default constructor",
   "class A { constructor(x){this.x=x} } class B extends A{}; new B(3).x"},
  {"object spread getter", "let o={get x(){return 2}}; ({...o}).x"},
  {"object assign getter", "let o={get x(){return 2}}; Object.assign({}, o).x"},
  {"array destructuring elision", "let [,x]=[1,2]; x"},
  {"array destructuring rest elision", "let [,,...r]=[1,2,3,4]; r.length"},
  {"object destructuring rename default", "let {x:y=3}={}; y"},
  {"parameter default later", "function f(a,b=a+1){return b} f(2)"},
  {"parameter rest destructuring", "function f(...[a,b]){return a+b} f(1,2)"},
  {"arrow destructuring param", "(({x})=>x)({x:4})"},
  {"nested arrow lexical arguments", "function f(){ return (()=>arguments[0])(2) } f(5)"},
  {"nested arrow lexical new target", "function F(){ return (()=>new.target===F)() } new F()"},
  {"unicode identifier", "let π=3; π"},
  {"escaped identifier", "let \u0061=4; a"},
  {"reserved property", "({default: 1}).default"},
  {"numeric separator", "1_000 + 2"},
  {"binary numeric", "0b1010"},
  {"octal numeric", "0o10"},
  {"hex bigint", "0xffn"},
  {"proxy get receiver", "let p=new Proxy({x:1},{get(t,k,r){return r===p?2:0}}); p.x"},
  {"proxy set receiver", "let p=new Proxy({}, {set(t,k,v,r){t[k]=v; return r===p}}); p.x=3"},
  {"proxy delete property",
   "let p=new Proxy({x:1},{deleteProperty(t,k){delete t[k]; return true}}); delete p.x"},
  {"proxy get own descriptor",
   "let p=new Proxy({x:1},{getOwnPropertyDescriptor(t,k){return Object.getOwnPropertyDescriptor(t,k)}}); Object.keys(p).length"},
  {"reflect apply type", "typeof Reflect.apply"},
  {"reflect get receiver", "let o={get x(){return this.y}}; Reflect.get(o,'x',{y:4})"},
  {"reflect set receiver", "let o={set x(v){this.y=v}}; let r={}; Reflect.set(o,'x',5,r); r.y"},
  {"object to string", "Object.prototype.toString.call([])"},
  {"array is array", "Array.isArray([])"},
  {"array of", "Array.of(1,2).length"},
  {"array from string length", "Array.from('ab').length"},
  {"array from map fn", "Array.from([1,2], x=>x+1)[1]"},
  {"string raw", "String.raw`a${1}b`"},
  {"string from char code", "String.fromCharCode(65,66)"},
  {"number parse int", "Number.parseInt('10', 10)"},
  {"number max safe type", "typeof Number.MAX_SAFE_INTEGER"},
  {"math pow", "Math.pow(2,4)"},
  {"math ceil", "Math.ceil(1.2)"},
  {"math floor", "Math.floor(1.8)"},
  {"math round", "Math.round(1.5)"},
  {"math sqrt", "Math.sqrt(9)"},
  {"math log type", "typeof Math.log(1)"},
  {"date value of", "new Date(0).valueOf()"},
  {"date to string type", "typeof new Date(0).toString()"},
  {"date now finite", "Number.isFinite(Date.now())"},
  {"uint32 overflow", "let a=new Uint32Array(1); a[0]=-1; a[0]"},
  {"int16 overflow", "let a=new Int16Array(1); a[0]=32768; a[0]"},
  {"float64 value", "let a=new Float64Array(1); a[0]=1.25; a[0]"},
  {"typed array join", "new Uint8Array([1,2]).join('-')"},
  {"typed array reverse", "let a=new Uint8Array([1,2]); a.reverse()[0]"},
  {"arraybuffer slice", "new ArrayBuffer(4).slice(1).byteLength"},
  {"url to string", "new URL('https://x.test/a').toString()"},
  {"urlsearchparams has", "new URLSearchParams('a=1').has('a')"},
  {"urlsearchparams get all length", "new URLSearchParams('a=1&a=2').getAll('a').length"},
  {"headers append",
   "let h=new Headers(); h.append('x','a'); h.append('x','b'); typeof h.get('x')"},
  {"formdata has", "let f=new FormData(); f.append('x','y'); f.has('x')"},
  {"formdata delete", "let f=new FormData(); f.append('x','y'); f.delete('x'); f.has('x')"},
  {"blob type", "new Blob(['x'], {type:'text/plain'}).type"},
  {"textdecoder empty", "new TextDecoder().decode(new Uint8Array()).length"},
  {"promise all empty", "async function f(){ let r=await Promise.all([]); return r.length } f()"},
  {"promise race pending type", "typeof Promise.race([]).then"},
  {"promise resolve primitive then type", "typeof Promise.resolve(1).then"},
  {"async throw caught outside catch",
   "async function f(){ try { throw new Error('x') } catch(e){ return e.message } } f()"},
  {"async await nonthenable object", "async function f(){ let o={x:1}; return (await o).x } f()"},
  {"async await thenable object", "async function f(){ return await {then(r){r(6)}} } f()"},
  {"generator multiple objects",
   "function* g(){ yield {x:1}; yield {x:2} } let it=g(); it.next(); it.next().value.x"},
  {"generator return done value",
   "function* g(){ return 5 } let r=g().next(); r.done && r.value"},
  {"generator yield false", "function* g(){ yield false } g().next().value"},
  {"async generator function type", "async function* g(){ yield 1 } typeof g"},
  {"class anonymous name", "let A = class {}; A.name"},
  {"class named expression inner", "let A = class B { static m(){return B.name} }; A.m()"},
  {"class extends null type",
   "class A extends null { constructor(){ return Object.create(null) } }; typeof new A()"},
  {"field initializer order", "class A { a=1; b=this.a+1 } new A().b"},
  {"private field initializer order", "class A { #a=1; b=this.#a+1 } new A().b"},
  {"super in field arrow",
   "class A { m(){return 1} } class B extends A { f=()=>super.m()+1 } new B().f()"},
  {"method name property", "({foo(){}}).foo.name"},
  {"computed method name property", "let k='foo'; ({[k](){}}).foo.name"},
  {"getter name property", "Object.getOwnPropertyDescriptor({get x(){}}, 'x').get.name"},
  {"setter name property", "Object.getOwnPropertyDescriptor({set x(v){}}, 'x').set.name"},
  {"function length", "function f(a,b=1,...r){}; f.length"},
  {"arrow length", "((a,b=1)=>{}).length"},
  {"bound function length", "function f(a,b){}; f.bind(null,1).length"},
  {"bound function name", "function f(){}; f.bind(null).name"},
  {"constructor name", "function F(){}; new F().constructor.name"},
  {"object create null typeof", "typeof Object.create(null)"},
  {"object define enumerable keys",
   "let o={}; Object.defineProperty(o,'x',{value:1, enumerable:false}); Object.keys(o).length"},
  {"object seal type only", "typeof Object.seal"},
  {"object prevent extensions type", "typeof Object.preventExtensions"},
  {"reflect own keys type", "typeof Reflect.ownKeys"},
  {"reflect construct type", "typeof Reflect.construct"},
  {"map constructor empty", "new Map().size"},
  {"set constructor empty", "new Set().size"},
  {"map has missing", "new Map([[1,2]]).has(3)"},
  {"set has missing", "new Set([1]).has(3)"},
  {"map set chaining", "let m=new Map(); m.set(1,2).set(3,4).size"},
  {"set add chaining", "let s=new Set(); s.add(1).add(2).size"},
  {"weakmap missing get", "let m=new WeakMap(); m.get({})"},
  {"weakset missing has", "let s=new WeakSet(); s.has({})"},
  {"json stringify undefined", "JSON.stringify(undefined)"},
  {"json stringify null", "JSON.stringify(null)"},
  {"json stringify bigint type", "try { JSON.stringify(1n) } catch(e){ e.name }"},
  {"parse int radix 16", "parseInt('ff', 16)"},
  {"is finite string", "isFinite('10')"},
  {"class private static inheritance false",
   "class A { static #x=1; static has(o){return #x in o} } class B extends A{}; A.has(B)"},
  {"class private static self true",
   "class A { static #x=1; static has(o){return #x in o} } A.has(A)"},
  {"super static field read",
   "class A { static x=1 } class B extends A { static m(){return super.x} } B.m()"},
  {"super static getter read",
   "class A { static get x(){return 2} } class B extends A { static m(){return super.x} } B.m()"},
  {"computed static block field", "let k='x'; class A { static { this[k]=3 } } A.x"},
  {"decorator identifier", "let decorator = 1; decorator"},
  {"nested eval expression", "function f(){ return eval('1+2') } f()"},
  {"eval this", "function f(){ return eval('this') === globalThis } f.call(globalThis)"},
  {"eval arrow", "eval('(()=>3)()')"},
  {"with method fixed", "let o={x:1,m(){return this.x}}; with(o){ m() }"},
  {"with fallback read", "var x=2; let o={}; with(o){ x }"},
  {"with unscopables method fallback",
   "function m(){return 3}; let o={m(){return 1}, [Symbol.unscopables]: {m:true}}; with(o){ m() }"},
  {"labeled function expression", "let f = function(){ label: { break label; } return 4 }; f()"},
  {"continue outer accumulation",
   "let s=0; outer: for(let i=0;i<3;i++){ for(let j=0;j<3;j++){ if(j===1) continue outer; s++ }} s"},
  {"break inner accumulation",
   "let s=0; for(let i=0;i<3;i++){ for(let j=0;j<3;j++){ if(j===1) break; s++ }} s"},
  {"for in continue",
   "let s=''; for (let k in {a:1,b:2,c:3}) { if(k==='b') continue; s+=k } s.length"},
  {"for of break", "let s=0; for (let x of [1,2,3]) { if(x===3) break; s+=x } s"},
  {"try finally continue", "let s=0; for(let i=0;i<2;i++){ try { continue } finally { s++ } } s"},
  {"try finally break", "let s=0; while(true){ try { break } finally { s=2 } } s"},
  {"throw primitive catch", "try { throw 'x' } catch(e) { e+'y' }"},
  {"throw object catch", "try { throw {x:1} } catch(e) { e.x }"},
  {"nested catch shadow", "try { throw 1 } catch(e) { try { throw 2 } catch(e) { e } }"},
  {"catch destructuring", "try { throw {x:3} } catch({x}) { x }"},
  {"finally preserves throw type",
   "try { try { throw new Error('x') } finally {} } catch(e) { e.message }"},
  {"switch lexical scoped", "let x=0; switch(1){case 1: { let y=2; x=y } } x"},
  {"switch default only", "let x=0; switch(2){default:x=3} x"},
  {"do while break", "let x=0; do { x++; break } while(true); x"},
  {"while continue", "let i=0,s=0; while(i<3){ i++; if(i===2) continue; s+=i } s"},
  {"for empty clauses", "let i=0; for(;;){ if(i++===2) break } i"},
  {"for in var", "var k; for (k in {x:1}) {} k"},
  {"for of var", "var x; for (x of [3]) {} x"},
  {"destructuring for of const", "let s=0; for (const {x} of [{x:1},{x:2}]) s+=x; s"},
  {"computed assignment destructuring", "let o={}, k='x'; ({a: o[k]} = {a:4}); o.x"},
  {"array assignment destructuring", "let a=[]; [a[0], a[1]] = [1,2]; a[0]+a[1]"},
  {"object assignment default", "let x; ({x=5} = {}); x"},
  {"template raw length", "function tag(s){return s.raw.length}; tag`a\nb`"},
  {"template cooked undefined", "function tag(s){return s[0] === undefined}; tag`\\unicode`"},
  {"array sort numeric comparator", "[3,1,2].sort((a,b)=>a-b).join('')"},
  {"array every thisarg", "[1].every(function(x){return this.v===x},{v:1})"},
  {"array some thisarg", "[1].some(function(x){return this.v===x},{v:1})"},
  {"array map thisarg", "[1].map(function(x){return x+this.v},{v:2})[0]"},
  {"array filter thisarg", "[1,2].filter(function(x){return x>this.v},{v:1}).length"},
  {"array reduce no init", "[1,2,3].reduce((a,b)=>a+b)"},
  {"array holes length", "let a=[]; a[2]=3; a.length"},
  {"array sparse keys", "let a=[]; a[2]=3; Object.keys(a).length"},
  {"array delete then length", "let a=[1,2]; delete a[0]; a.length"},
  {"array concat sparse length", "let a=[1,,3]; a.concat([4]).length"},
  {"object spread symbol", "let s=Symbol('s'); let o={...{[s]:2}}; o[s]"},
  {"object spread multiple getters",
   "let o={get x(){return 1}}, p={get y(){return 2}}; let r={...o,...p}; r.x+r.y"},
  {"object from entries symbol", "let s=Symbol('s'); Object.fromEntries([[s,4]])[s]"},
  {"object assign symbol", "let s=Symbol('s'); Object.assign({}, {[s]:5})[s]"},
  {"object define symbol", "let s=Symbol('s'), o={}; Object.defineProperty(o,s,{value:6}); o[s]"},
  {"symbol iterator equality", "Symbol.iterator === Symbol.iterator"},
  {"symbol async iterator type", "typeof Symbol.asyncIterator"},
  {"symbol has instance type", "typeof Symbol.hasInstance"},
  {"symbol to string tag type", "typeof Symbol.toStringTag"},
  {"custom tostringtag", "let o={[Symbol.toStringTag]:'X'}; Object.prototype.toString.call(o)"},
  {"spread iterator custom",
   "let it={ [Symbol.iterator](){let i=0; return {next(){return i++<2?{value:i,done:false}:{done:true}}}}}; [...it].length"},
  {"call spread iterator", "function f(a,b){return a+b}; let it=[1,2]; f(...it)"},
  {"new spread iterator", "function F(a,b){this.x=a+b}; new F(...[1,2]).x"},
  {"template tag expression order",
   "let s=''; function tag(a,...v){return s}; tag`${s+='a'}${s+='b'}`"},
  {"template nested", "`${`a${1}`}${2}`"},
  {"regexp unicode flag type", "/a/u.unicode"},
  {"regexp has indices type", "typeof /a/d.hasIndices"},
  {"regexp last index set", "let r=/a/g; r.lastIndex=1; r.lastIndex"},
  {"regexp exec null", "/z/.exec('abc') === null"},
  {"regexp test false", "/z/.test('abc')"},
  {"string iterator manual type", "typeof 'a'[Symbol.iterator]"},
  {"unicode string length", "'😀'.length"},
  {"string at", "'abc'.at(-1)"},
  {"string trim start", "' x'.trimStart()"},
  {"string trim end", "'x '.trimEnd()"},
  {"string repeat zero", "'x'.repeat(0)"},
  {"number nan objectis", "Object.is(Number.NaN, NaN)"},
  {"math max no args", "Math.max()"},
  {"math sign negative zero", "Object.is(Math.sign(-0), -0)"},
  {"math trunc negative", "Math.trunc(-1.9)"},
  {"math cbrt type", "typeof Math.cbrt(8)"},
  {"optional chain delete nested", "let o={}; delete o.a?.b"},
  {"optional element call", "let o={f(){return 1}}; o?.['f']?.()"},
  {"optional element missing", "let o={}; o?.['x']?.y === undefined"},
  {"nullish assignment array", "let a=[]; a[0] ??= 3; a[0]"},
  {"or assignment array", "let a=[0]; a[0] ||= 3; a[0]"},
  {"and assignment array", "let a=[1]; a[0] &&= 3; a[0]"},
  {"compound add property", "let o={x:1}; o.x += 2; o.x"},
  {"compound mul element", "let a=[2]; a[0] *= 3; a[0]"},
  {"post inc element", "let a=[1]; a[0]++; a[0]"},
  {"pre inc property", "let o={x:1}; ++o.x"},
  {"private field compound", "class A { #x=1; m(){ this.#x += 2; return this.#x } } new A().m()"},
  {"static private field compound",
   "class A { static #x=1; static m(){ this.#x += 2; return this.#x } } A.m()"},
  {"super compound field",
   "class A { set x(v){this.y=v} get x(){return this.y||1} } class B extends A { m(){ super.x += 2; return this.y } } new B().m()"},
  {"destructuring assignment rest object", "let r; ({a: r, ...rest} = {a:1,b:2}); r"},
  {"destructuring assignment nested", "let x; ({a:{b:x}} = {a:{b:4}}); x"},
  {"destructuring assignment default fn", "let x; [x = (()=>5)()] = []; x"},
  {"destructuring parameter default fn", "function f([x=(()=>6)()]){return x}; f([])"},
  {"object literal duplicate keys", "({x:1,x:2}).x"},
  {"object literal numeric key", "({1: 'a'})[1]"},
  {"object literal bigint key", "({[1n]: 'a'})['1']"},
  {"class field string name", "class A {'x'=1} new A().x"},
  {"class field numeric name", "class A {1=2} new A()[1]"},
  {"class method string name", "class A {'m'(){return 3}} new A().m()"},
  {"class getter numeric", "class A { get 1(){return 5}} new A()[1]"},
  {"static method name property", "class A { static m(){} } A.m.name"},
  {"private method name type", "class A { #m(){} m(){return typeof this.#m} } new A().m()"},
  {"constructor returns this", "class A { constructor(){ return this } } new A() instanceof A"},
  {"base constructor primitive return",
   "class A { constructor(){ return 1 } } new A() instanceof A"},
  {"derived no explicit constructor",
   "class A { constructor(){this.x=1} } class B extends A {} new B().x"},
  {"new target in arrow in constructor",
   "class A { constructor(){ this.v=(()=>new.target===A)() } } new A().v"},
  {"arguments in arrow method", "let o={m(){return (()=>arguments.length)(1)}}; o.m(1,2)"},
  {"function caller type", "function f(){return typeof f.caller}; f()"},
  {"function arguments type", "function f(){return typeof f.arguments}; f()"},
  {"arguments index write", "function f(a){ arguments[0]=3; return arguments[0] } f(1)"},
  {"arguments parameter write", "function f(a){ a=3; return arguments[0] } f(1)"},
  {"rest param array methods", "function f(...xs){ xs.push(3); return xs.length } f(1,2)"},
  {"default param scope", "let x=1; function f(a=x){let x=2; return a} f()"},
  {"const assignment caught", "const x=1; try { x=2 } catch(e){ e.name }"},
  {"global var delete", "var x=1; delete x"},
  {"global lexical delete", "let y=1; delete y"},
  {"function declaration block sloppy", "if (true) function f(){return 1}; f()"},
  {"class declaration block scope", "let t=typeof A; { class A {} } t"},
  {"for await type nested",
   "async function f(){ for await (const x of [1,2]) { return x } } typeof f"},
  {"array flat empty", "[, [1]].flat().length"},
  {"array flat depth zero", "[1,[2]].flat(0).length"},
  {"array flatmap thisarg", "[1].flatMap(function(x){return [x+this.v]}, {v:2})[0]"},
  {"array copywithin negative", "let a=[1,2,3]; a.copyWithin(-1,0,1); a[2]"},
  {"array fill negative", "let a=[1,2,3]; a.fill(9,-1); a[2]"},
  {"array slice negative", "[1,2,3].slice(-2).length"},
  {"array splice insert", "let a=[1,3]; a.splice(1,0,2); a.join('')"},
  {"array find thisarg", "[1,2].find(function(x){return x===this.v},{v:2})"},
  {"array findindex thisarg", "[1,2].findIndex(function(x){return x===this.v},{v:2})"},
  {"array includes from negative", "[1,2,3].includes(2,-2)"},
  {"array at positive", "[1,2,3].at(1)"},
  {"string slice negative", "'abc'.slice(-2)"},
  {"string substring reversed", "'abc'.substring(3,1)"},
  {"string startswith pos", "'abc'.startsWith('b',1)"},
  {"string endswith len", "'abc'.endsWith('b',2)"},
  {"string padstart default", "'x'.padStart(3)"},
  {"string repeat two", "'xy'.repeat(2)"},
  {"string split limit", "'a,b,c'.split(',',2).length"},
  {"string replace function", "'abc'.replace('b', function(){return 'X'})"},
  {"regexp replace function", "'abc'.replace(/b/, function(m){return m.toUpperCase()})"},
  {"regexp constructor type", "typeof RegExp"},
  {"regexp prototype type", "typeof RegExp.prototype.test"},
  {"date utc type", "typeof Date.UTC(2020,0,1)"},
  {"date parse finite", "Number.isFinite(Date.parse('1970-01-01T00:00:00Z'))"},
  {"date get utc full year", "new Date(0).getUTCFullYear()"},
  {"date toISOString epoch", "new Date(0).toISOString().startsWith('1970')"},
  {"math acos type", "typeof Math.acos(1)"},
  {"math atan2 type", "typeof Math.atan2(1,1)"},
  {"math exp type", "typeof Math.exp(1)"},
  {"math log10 type", "typeof Math.log10(100)"},
  {"math max negatives", "Math.max(-3,-1,-2)"},
  {"number is finite false", "Number.isFinite('1')"},
  {"object values symbol ignored", "let s=Symbol('s'); Object.values({[s]:1,a:2}).length"},
  {"object entries order basic", "Object.entries({a:1,b:2}).map(x=>x[0]).join('')"},
  {"object create descriptor", "let o=Object.create(null,{x:{value:3, enumerable:true}}); o.x"},
  {"object assign primitive", "Object.assign({}, 'ab')[0]"},
  {"reflect get missing", "Reflect.get({}, 'x')"},
  {"reflect set new prop", "let o={}; Reflect.set(o,'x',1); o.x"},
  {"reflect delete type", "typeof Reflect.deleteProperty"},
  {"proxy get missing", "let p=new Proxy({}, {get(t,k){return k==='x'?1:undefined}}); p.x"},
  {"proxy has false", "let p=new Proxy({}, {has(){return false}}); 'x' in p"},
  {"map object key", "let k={}; let m=new Map(); m.set(k,2); m.get(k)"},
  {"set object key", "let k={}; let s=new Set(); s.add(k); s.has(k)"},
  {"weakmap overwrite", "let k={}; let m=new WeakMap(); m.set(k,1); m.set(k,2); m.get(k)"},
  {"weakset duplicate", "let k={}; let s=new WeakSet(); s.add(k); s.add(k); s.has(k)"},
  {"json parse nested", "JSON.parse('{\"a\":[1,2]}').a[1]"},
  {"json stringify string", "JSON.stringify('x')"},
  {"json stringify boolean", "JSON.stringify(true)"},
  {"json stringify number", "JSON.stringify(3)"},
  {"url hash set", "let u=new URL('https://x.test/a'); u.hash='x'; u.hash"},
  {"urlsearchparams set", "let p=new URLSearchParams('a=1'); p.set('a','2'); p.get('a')"},
  {"urlsearchparams delete", "let p=new URLSearchParams('a=1'); p.delete('a'); p.has('a')"},
  {"headers keys type", "let h=new Headers({'x':'y'}); typeof h.keys"},
  {"formdata entries type", "let f=new FormData(); typeof f.entries"},
  {"blob arraybuffer type", "typeof new Blob(['x']).arrayBuffer"},
  {"crypto random values same object",
   "let a=new Uint8Array(1); crypto.getRandomValues(a) === a"},
  {"performance now finite", "Number.isFinite(performance.now())"},
  {"async object method resolved", "let o={async m(){return await 11}}; o.m()"},
  {"async class method resolved", "class A { async m(){return await 12} } new A().m()"},
  {"async object method this", "let o={x:3, async m(){return await this.x}}; o.m()"},
  {"with object base read method", "let o={a:{m(){return 7}}}; with(o){ a.m() }"},
  {"with object property read", "let o={x:2}; with(o){ x }"},
  {"with lexical fallback read", "let o={}; let x=1; with(o){ x }"},
  {"with unscopables fallback read",
   "var x=1; let o={x:2,[Symbol.unscopables]:{x:true}}; with(o){ x }"},
  {"eval with ref assignment",
   "function f(){ var x=1; function g(){ eval(''); x=2; return x }; return g() } f()"},
  {"spread ascii string", "[...'ab'].join('')"},
  {"spread astral string", "[...'😀'].length"},
  {"delete array element missing", "let a=[1]; delete a[0]; 0 in a"},
  {"delete array element read", "let a=[1]; delete a[0]; a[0] === undefined"},
  {"atom cache distinct pad start", "'x'.padStart(3,'a')"},
  {"atom cache distinct pad end", "'x'.padEnd(3,'a')"},
  {"object keys numeric order", "Object.keys({2:1,1:1,a:1}).join(',')"},
  {"object values numeric order", "Object.values({2:'b',1:'a',z:'c'}).join(',')"},
  {"object entries numeric order",
   "Object.entries({2:'b',1:'a',z:'c'}).map(e=>e[0]+e[1]).join(',')"},
  {"object prototype hasOwnProperty", "({x:1}).hasOwnProperty('x')"},
  {"object prototype toString", "({}).toString()"},
  {"typed array includes hit", "new Uint8Array([1,2,3]).includes(2)"},
  {"typed array includes miss", "new Uint8Array([1,2,3]).includes(4)"},
  {"sloppy direct call this", "function f(){ return this===globalThis}; f()"},
  {"strict direct call this", "function f(){'use strict'; return this===undefined}; f()"},
  {"tdz typeof guard", "try { typeof x } catch(e) { e.name } let x=1"},
  {"nested private brand",
   "class A{ #x=1; m(){ class B{ n(o){ return o.#x } } return new B().n(this) } } new A().m()"},
  {"private in brand", "class A{ #x; static has(o){return #x in o} } A.has(new A())"},
  {"reflect delete property", "let o={x:1}; Reflect.deleteProperty(o,'x'); o.x===undefined"},
  {"reflect define property",
   "let o={}; Reflect.defineProperty(o,'x',{value:2, enumerable:true}); o.x"},
  {"reflect define non-enumerable",
   "let o={}; Reflect.defineProperty(o,'x',{value:2, enumerable:false}); Object.keys(o).length"},
  {"url canParse true", "URL.canParse('https://x.test/')"},
  {"url canParse false", "URL.canParse('not a url')"},
  {"event constructor type", "new Event('tick', {bubbles:true}).type"},
  {"event constructor bubbles", "new Event('tick', {bubbles:true}).bubbles"},
  {"regexp dotAll test", "/a.b/s.test('a\\nb')"},
  {"regexp flags unicode dotAll", "/./su.flags"},
  {"symbol registry equality", "Symbol.for('x')===Symbol.for('x')"},
  {"symbol registry keyFor", "Symbol.keyFor(Symbol.for('x'))"},
  {"symbol description", "Symbol('x').description"},
  {"bigint toString", "(10n).toString()"},
  {"bigint add", "1n + 2n"}
]

auto_cases = [
  {"auto mode arithmetic", "function inc(x){ return x + 1 } inc(2)"},
  {"auto mode method receiver", "let o={x:3, inc(y){ return this.x + y }}; o.inc(4)"},
  {"auto mode throw", "try { throw new Error('boom') } catch (e) { e.message }"}
]

results =
  Enum.map(cases, fn {name, source} -> QuickBEAM.VM.CompilerAudit.run_case(name, source) end) ++
    Enum.map(auto_cases, fn {name, source} ->
      QuickBEAM.VM.CompilerAudit.run_auto_case(name, source)
    end)

summary = QuickBEAM.VM.CompilerAudit.summary(results)
failures = summary.fallbacks + summary.crashes + summary.mismatches + summary.input_errors

IO.puts(
  "compiler_semantic_cases=#{summary.cases} compiler_semantic_compiled=#{summary.compiled} compiler_semantic_failures=#{failures} compiler_semantic_fallbacks=#{summary.fallbacks} compiler_semantic_crashes=#{summary.crashes} compiler_semantic_mismatches=#{summary.mismatches} compiler_semantic_input_errors=#{summary.input_errors}"
)

for result <- results, result.status != :compiled do
  IO.puts("COMPILER_SEMANTIC_#{String.upcase(to_string(result.status))} #{result.name}")
  IO.puts("  source=#{result.source}")
  IO.puts("  interpreter=#{inspect(result.interpreter)}")
  IO.puts("  compiler=#{inspect(result.compiler)}")
end

IO.puts("METRIC compiler_semantic_cases=#{summary.cases}")
IO.puts("METRIC compiler_semantic_compiled=#{summary.compiled}")
IO.puts("METRIC compiler_semantic_failures=#{failures}")
IO.puts("METRIC compiler_semantic_fallbacks=#{summary.fallbacks}")
IO.puts("METRIC compiler_semantic_crashes=#{summary.crashes}")
IO.puts("METRIC compiler_semantic_mismatches=#{summary.mismatches}")
IO.puts("METRIC compiler_semantic_input_errors=#{summary.input_errors}")
