defmodule QuickBEAM.VM.Builtin do
  @moduledoc "Macros for defining JS builtins: `proto`, `static`, `js_object`, `build_methods`, and `build_object`."

  @doc """
  Uniform macros for defining JS builtins in all contexts.

  All builtins use 2-arity `fn args, this ->` convention.

  ## Module-level dispatch (generates def clauses)

      proto "push" do ... end         # → def proto_property("push")
      static "isArray" do ... end     # → def static_property("isArray")
      static_val "PI", :math.pi()    # → def static_property("PI"), do: value

  ## Named object (generates def object/0)

      js_object "Math" do
        method "floor" do ... end
        val "PI", :math.pi()
      end

  ## Inline maps (returns %{} at call site)

      build_methods do              # returns %{"name" => {:builtin, ...}, ...}
        method "add" do ... end
        val "size", 0
      end

      build_object do               # returns Heap.wrap(%{"name" => {:builtin, ...}, ...})
        method "add" do ... end
        val "size", 0
      end

  `args` and `this` are injected in all `proto`/`static`/`method` bodies.
  Catch-all fallbacks are auto-generated by @before_compile.
  """

  defmacro __using__(_opts) do
    quote do
      import QuickBEAM.VM.Builtin,
        only: [
          proto: 2,
          static: 2,
          static_val: 2,
          js_object: 2,
          build_methods: 1,
          build_object: 1
        ]

      Module.register_attribute(__MODULE__, :__has_proto, accumulate: false)
      Module.register_attribute(__MODULE__, :__has_static, accumulate: false)
      @before_compile QuickBEAM.VM.Builtin
    end
  end

  defmacro __before_compile__(env) do
    has_proto = Module.get_attribute(env.module, :__has_proto)
    has_static = Module.get_attribute(env.module, :__has_static)

    proto_fallback =
      if has_proto do
        quote do: def(proto_property(_), do: :undefined)
      end

    static_fallback =
      if has_static do
        quote do: def(static_property(_), do: :undefined)
      end

    [proto_fallback, static_fallback]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> nil
      blocks -> {:__block__, [], blocks}
    end
  end

  # ── Module-level dispatch macros ──

  defmacro proto(name, do: body) do
    quote do
      @__has_proto true
      def proto_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end
    end
  end

  defmacro static(name, do: body) do
    quote do
      @__has_static true
      def static_property(unquote(name)) do
        unquote(build_builtin(name, body))
      end
    end
  end

  defmacro static_val(name, value) do
    quote do
      @__has_static true
      def static_property(unquote(name)), do: unquote(value)
    end
  end

  # ── Named object macro ──

  defmacro js_object(name, do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)

    quote do
      def object do
        {:builtin, unquote(name), %{unquote_splicing(map_entries)}}
      end
    end
  end

  # ── Inline map/list macros ──

  defmacro build_methods(do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)
    quote do: %{unquote_splicing(map_entries)}
  end

  defmacro build_object(do: block) do
    entries = normalize_block(block)
    map_entries = Enum.map(entries, &build_map_entry/1)

    quote do
      QuickBEAM.VM.Heap.wrap(%{unquote_splicing(map_entries)})
    end
  end

  # ── Shared builders ──

  defp build_builtin(name, body) do
    quote do
      {:builtin, unquote(name),
       fn var!(args), var!(this) ->
         _ = var!(args)
         _ = var!(this)
         unquote(body)
       end}
    end
  end

  defp normalize_block({:__block__, _, entries}), do: entries
  defp normalize_block(single), do: [single]

  defp build_map_entry({:method, _, [name, [do: body]]}) do
    {name, build_builtin(name, body)}
  end

  defp build_map_entry({:val, _, [name, value]}) do
    {name, value}
  end

  # ── Runtime dispatch ──

  alias QuickBEAM.VM.Bytecode
  alias QuickBEAM.VM.JSThrow

  def call({:builtin, _, cb}, args, this), do: cb.(args, this)

  def call({:bound, _, inner, _, _}, args, this), do: call(inner, args, this)

  def call(f, args, _this) when is_function(f, 2), do: f.(args, nil)

  def call(f, args, _this) when is_function(f, 1), do: f.(args)

  def call(f, args, _this) when is_function(f), do: apply(f, args)

  def call(_, _, _),
    do: JSThrow.type_error!("not a function")

  def callable?(%Bytecode.Function{}), do: true

  def callable?({:closure, _, %Bytecode.Function{}}), do: true

  def callable?({:builtin, _, _}), do: true

  def callable?({:bound, _, _, _, _}), do: true

  def callable?(f) when is_function(f), do: true

  def callable?(_), do: false
end
