{application,pegasus,
             [{modules,['Elixir.Pegasus','Elixir.Pegasus.Ast',
                        'Elixir.Pegasus.Class','Elixir.Pegasus.Components',
                        'Elixir.Pegasus.Expression','Elixir.Pegasus.Grammar',
                        'Elixir.Pegasus.Identifier','Elixir.Pegasus.Literal',
                        'Elixir.Pegasus.Primary','Elixir.Pegasus.Sequence',
                        'Elixir.Pegasus.Tokens']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,nimble_parsec]},
              {description,"peg -> nimbleparsec"},
              {registered,[]},
              {vsn,"0.2.6"}]}.
