defmodule QuickBEAM.VM.Program.Function do
  @moduledoc "JavaScript function metadata and pre-resolved VM instructions used by the interpreter and BEAM compiler."

  defstruct [
    :id,
    :name,
    :filename,
    line_num: 1,
    col_num: 1,
    pc2line: <<>>,
    source: <<>>,
    source_positions: nil,
    arg_count: 0,
    var_count: 0,
    defined_arg_count: 0,
    stack_size: 0,
    var_ref_count: 0,
    locals: [],
    closure_vars: [],
    constants: [],
    atoms: nil,
    instructions: nil,
    has_prototype: false,
    has_simple_parameter_list: false,
    is_derived_class_constructor: false,
    need_home_object: false,
    func_kind: 0,
    new_target_allowed: false,
    super_call_allowed: false,
    super_allowed: false,
    arguments_allowed: false,
    is_strict_mode: false,
    has_debug_info: false
  ]

  @type t :: %__MODULE__{
          id: non_neg_integer(),
          name: String.t(),
          filename: String.t() | nil,
          line_num: pos_integer(),
          col_num: pos_integer(),
          pc2line: binary(),
          source: binary(),
          source_positions: tuple(),
          arg_count: non_neg_integer(),
          var_count: non_neg_integer(),
          defined_arg_count: non_neg_integer(),
          stack_size: non_neg_integer(),
          var_ref_count: non_neg_integer(),
          locals: [QuickBEAM.VM.Program.Variable.t()],
          closure_vars: [QuickBEAM.VM.Program.Variable.Closure.t()],
          constants: [term()],
          atoms: tuple(),
          instructions: tuple(),
          has_prototype: boolean(),
          has_simple_parameter_list: boolean(),
          is_derived_class_constructor: boolean(),
          need_home_object: boolean(),
          func_kind: non_neg_integer(),
          new_target_allowed: boolean(),
          super_call_allowed: boolean(),
          super_allowed: boolean(),
          arguments_allowed: boolean(),
          is_strict_mode: boolean(),
          has_debug_info: boolean()
        }
end
